project_id = "dbekdedzgkfgtlytrnyw"

[functions.discord-callback]
verify_jwt = false

[functions.create-abacatepay-checkout]
verify_jwt = false

[functions.create-evopay-pix]
verify_jwt = false

[functions.check-evopay-status]
verify_jwt = false

[functions.evopay-webhook]
verify_jwt = false

[functions.evopay-withdraw]
verify_jwt = false

[functions.mark-order-delivered]
verify_jwt = false
