project_id = "dbekdedzgkfgtlytrnyw"

[functions.discord-callback]
verify_jwt = false

[functions.create-evopay-pix]
verify_jwt = false

[functions.create-purchase]
verify_jwt = false

[functions.check-evopay-status]
verify_jwt = false

[functions.evopay-webhook]
verify_jwt = false

[functions.evopay-withdraw]
verify_jwt = false

[functions.mark-order-delivered]
verify_jwt = false

[functions.order-action]
verify_jwt = false

[functions.integrations-config]
verify_jwt = false

[functions.create-zennith-pix]
verify_jwt = false

[functions.zennith-webhook]
verify_jwt = false

[functions.zennith-withdraw]
verify_jwt = false

[functions.create-vexopay-crypto]
verify_jwt = false
