-- ZXMAX · perguntas de anúncio persistentes e moderadas pelo banco.
-- A validação de contatos externos precisa existir no servidor: a interface nunca
-- é uma fronteira de segurança.

CREATE TABLE IF NOT EXISTS public.product_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  body text NOT NULL,
  answer text,
  answered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_questions_body_length CHECK (char_length(btrim(body)) BETWEEN 3 AND 1000),
  CONSTRAINT product_questions_answer_length CHECK (answer IS NULL OR char_length(btrim(answer)) BETWEEN 1 AND 2000)
);

CREATE INDEX IF NOT EXISTS product_questions_product_created_idx
  ON public.product_questions(product_id, created_at DESC);

ALTER TABLE public.product_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read product questions" ON public.product_questions;
CREATE POLICY "Anyone can read product questions"
  ON public.product_questions FOR SELECT USING (true);

-- Inserts and replies go exclusively through the RPCs below, which bind the
-- author/seller to auth.uid() and enforce the contact rule server-side.
REVOKE INSERT, UPDATE, DELETE ON public.product_questions FROM anon, authenticated;
GRANT SELECT ON public.product_questions TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.reject_external_contact(content text)
RETURNS void
LANGUAGE plpgsql
IMMUTABLE
SET search_path = public
AS $$
DECLARE
  normalized text := lower(coalesce(content, ''));
BEGIN
  -- Links, e-mail, phone numbers and common off-platform contact services.
  IF normalized ~ '(https?://|www\.|\.com\b|\.gg/|@[^[:space:]]+\.[a-z]{2,})'
     OR normalized ~ '(^|[^0-9])[0-9][0-9 .()_-]{7,}[0-9]([^0-9]|$)'
     OR normalized ~ '\m(whats(app)?|discord|telegram|instagram|email|e-mail)\M' THEN
    RAISE EXCEPTION 'Não é permitido enviar contatos externos (WhatsApp, Discord, e-mail, links ou telefone).'
      USING ERRCODE = '22023';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.ask_product_question(_product_id bigint, _body text)
RETURNS public.product_questions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  created_question public.product_questions;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Faça login para enviar uma pergunta.' USING ERRCODE = '42501';
  END IF;
  PERFORM public.reject_external_contact(_body);
  IF NOT EXISTS (SELECT 1 FROM public.products WHERE id = _product_id AND approved = true) THEN
    RAISE EXCEPTION 'Este anúncio não está disponível para perguntas.' USING ERRCODE = 'P0002';
  END IF;
  INSERT INTO public.product_questions(product_id, author_id, body)
  VALUES (_product_id, auth.uid(), btrim(_body))
  RETURNING * INTO created_question;
  RETURN created_question;
END;
$$;

CREATE OR REPLACE FUNCTION public.answer_product_question(_question_id bigint, _answer text)
RETURNS public.product_questions
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  answered_question public.product_questions;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Faça login para responder.' USING ERRCODE = '42501';
  END IF;
  PERFORM public.reject_external_contact(_answer);
  UPDATE public.product_questions q
     SET answer = btrim(_answer), answered_at = now()
    FROM public.products p
   WHERE q.id = _question_id
     AND p.id = q.product_id
     AND p.seller_id = auth.uid()
  RETURNING q.* INTO answered_question;
  IF answered_question.id IS NULL THEN
    RAISE EXCEPTION 'Você não tem permissão para responder esta pergunta.' USING ERRCODE = '42501';
  END IF;
  RETURN answered_question;
END;
$$;

REVOKE ALL ON FUNCTION public.ask_product_question(bigint, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.answer_product_question(bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ask_product_question(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.answer_product_question(bigint, text) TO authenticated;
