CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id uuid NOT NULL,
  seller_public_id text NOT NULL DEFAULT '',
  seller_email text NOT NULL DEFAULT '',
  seller_name text NOT NULL DEFAULT '',
  name text NOT NULL,
  price numeric(12,2) NOT NULL DEFAULT 0,
  category text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  banner text,
  description text NOT NULL DEFAULT '',
  approved boolean NOT NULL DEFAULT false,
  delivery_type text NOT NULL DEFAULT 'manual',
  delivery_content text,
  variations jsonb NOT NULL DEFAULT '[]'::jsonb,
  questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  sales integer NOT NULL DEFAULT 0,
  rating numeric(3,2) NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Approved products are public" ON public.products;
CREATE POLICY "Approved products are public"
ON public.products
FOR SELECT
USING (approved = true OR auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Users can create own products" ON public.products;
CREATE POLICY "Users can create own products"
ON public.products
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = seller_id);

DROP POLICY IF EXISTS "Sellers and admins can update products" ON public.products;
CREATE POLICY "Sellers and admins can update products"
ON public.products
FOR UPDATE
TO authenticated
USING (auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Sellers and admins can delete products" ON public.products;
CREATE POLICY "Sellers and admins can delete products"
ON public.products
FOR DELETE
TO authenticated
USING (auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TABLE IF NOT EXISTS public.purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  buyer_id uuid NOT NULL,
  buyer_public_id text NOT NULL DEFAULT '',
  buyer_email text NOT NULL DEFAULT '',
  seller_id uuid NOT NULL,
  seller_public_id text NOT NULL DEFAULT '',
  seller_email text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  amount numeric(12,2) NOT NULL DEFAULT 0,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  reviewed boolean NOT NULL DEFAULT false,
  review_stars integer,
  review_comment text,
  variation_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Purchase parties and admins can view" ON public.purchases;
CREATE POLICY "Purchase parties and admins can view"
ON public.purchases
FOR SELECT
TO authenticated
USING (auth.uid() = buyer_id OR auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Users can create own purchases" ON public.purchases;
CREATE POLICY "Users can create own purchases"
ON public.purchases
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = buyer_id);

DROP POLICY IF EXISTS "Purchase parties and admins can update" ON public.purchases;
CREATE POLICY "Purchase parties and admins can update"
ON public.purchases
FOR UPDATE
TO authenticated
USING (auth.uid() = buyer_id OR auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (auth.uid() = buyer_id OR auth.uid() = seller_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TABLE IF NOT EXISTS public.withdrawals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  user_public_id text NOT NULL DEFAULT '',
  user_email text NOT NULL DEFAULT '',
  amount numeric(12,2) NOT NULL DEFAULT 0,
  method text NOT NULL DEFAULT 'normal',
  status text NOT NULL DEFAULT 'pending',
  pix_key text NOT NULL DEFAULT '',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users and admins can view withdrawals" ON public.withdrawals;
CREATE POLICY "Users and admins can view withdrawals"
ON public.withdrawals
FOR SELECT
TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

DROP POLICY IF EXISTS "Users can create own withdrawals" ON public.withdrawals;
CREATE POLICY "Users can create own withdrawals"
ON public.withdrawals
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can update withdrawals" ON public.withdrawals;
CREATE POLICY "Admins can update withdrawals"
ON public.withdrawals
FOR UPDATE
TO authenticated
USING (public.has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (public.has_role(auth.uid(), 'admin'::app_role));

CREATE INDEX IF NOT EXISTS idx_products_approved_created ON public.products(approved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_seller ON public.products(seller_id);
CREATE INDEX IF NOT EXISTS idx_purchases_buyer ON public.purchases(buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchases_seller ON public.purchases(seller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_withdrawals_user_status ON public.withdrawals(user_id, status);

DROP TRIGGER IF EXISTS update_products_updated_at ON public.products;
CREATE TRIGGER update_products_updated_at
BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_purchases_updated_at ON public.purchases;
CREATE TRIGGER update_purchases_updated_at
BEFORE UPDATE ON public.purchases
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_withdrawals_updated_at ON public.withdrawals;
CREATE TRIGGER update_withdrawals_updated_at
BEFORE UPDATE ON public.withdrawals
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();