CREATE TABLE public.payment_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider text NOT NULL,
  event_key text NOT NULL,
  event_type text NOT NULL,
  purchase_id bigint REFERENCES public.purchases(id) ON DELETE SET NULL,
  charge_id text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  processed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, event_key)
);
GRANT ALL ON public.payment_events TO service_role;
ALTER TABLE public.payment_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.apply_verified_payment(
  _provider text,
  _event_key text,
  _event_type text,
  _purchase_id bigint,
  _charge_id text,
  _confirmed_amount numeric,
  _payload jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(applied boolean, resulting_status text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  purchase_row public.purchases%ROWTYPE;
  product_row public.products%ROWTYPE;
  delivery_text text;
  next_status text := 'paid';
  next_messages jsonb;
BEGIN
  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    RAISE EXCEPTION 'server_only';
  END IF;

  INSERT INTO public.payment_events(provider, event_key, event_type, purchase_id, charge_id, payload)
  VALUES (_provider, _event_key, _event_type, _purchase_id, _charge_id, COALESCE(_payload, '{}'::jsonb))
  ON CONFLICT (provider, event_key) DO NOTHING;

  IF NOT FOUND THEN
    SELECT p.status INTO resulting_status FROM public.purchases p WHERE p.id = _purchase_id;
    applied := false;
    RETURN NEXT;
    RETURN;
  END IF;

  SELECT * INTO purchase_row FROM public.purchases WHERE id = _purchase_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'purchase_not_found'; END IF;
  IF purchase_row.status <> 'pending' THEN
    resulting_status := purchase_row.status;
    applied := false;
    RETURN NEXT;
    RETURN;
  END IF;
  IF purchase_row.evopay_charge_id IS DISTINCT FROM _charge_id THEN RAISE EXCEPTION 'charge_mismatch'; END IF;
  IF purchase_row.amount IS DISTINCT FROM _confirmed_amount THEN RAISE EXCEPTION 'amount_mismatch'; END IF;

  SELECT * INTO product_row FROM public.products WHERE id = purchase_row.product_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'product_not_found'; END IF;
  next_messages := COALESCE(purchase_row.messages, '[]'::jsonb);

  IF product_row.delivery_type = 'auto' THEN
    SELECT delivery_content INTO delivery_text FROM public.product_delivery WHERE product_id = purchase_row.product_id;
    IF COALESCE(delivery_text, '') <> '' THEN
      next_status := 'delivered';
      next_messages := next_messages || jsonb_build_array(jsonb_build_object(
        'from', 'System',
        'text', '📦 ENTREGA_AUTO: ' || delivery_text,
        'date', now()
      ));
    END IF;
  END IF;

  UPDATE public.purchases
  SET status = next_status, messages = next_messages, updated_at = now()
  WHERE id = _purchase_id;
  UPDATE public.products SET sales = COALESCE(sales, 0) + 1 WHERE id = purchase_row.product_id;

  applied := true;
  resulting_status := next_status;
  RETURN NEXT;
END;
$$;
REVOKE ALL ON FUNCTION public.apply_verified_payment(text,text,text,bigint,text,numeric,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_verified_payment(text,text,text,bigint,text,numeric,jsonb) TO service_role;

REVOKE ALL ON public.purchases FROM anon, authenticated;
GRANT SELECT (id, product_id, buyer_id, buyer_public_id, seller_id, seller_public_id, status, amount, messages, reviewed, review_stars, review_comment, variation_name, created_at, updated_at, evopay_charge_id, pix_qr_code, pix_expires_at) ON public.purchases TO authenticated;
GRANT UPDATE (reviewed, review_stars, review_comment, updated_at) ON public.purchases TO authenticated;
GRANT ALL ON public.purchases TO service_role;
DROP POLICY IF EXISTS "Buyers can review delivered purchases" ON public.purchases;
CREATE POLICY "Buyers can review completed purchases"
ON public.purchases FOR UPDATE TO authenticated
USING (buyer_id = auth.uid() AND status = 'delivered')
WITH CHECK (buyer_id = auth.uid() AND status = 'delivered');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'purchases'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.purchases;
  END IF;
END $$;
ALTER TABLE public.purchases REPLICA IDENTITY FULL;