create table if not exists public.refund_requests (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null unique references public.purchases(id) on delete cascade,
  buyer_id uuid not null,
  seller_id uuid not null,
  reason text not null,
  status text not null default 'awaiting_buyer_details' check (status in ('awaiting_buyer_details','ready_to_pay','paid','cancelled')),
  account_holder_name text,
  pix_key text,
  requested_at timestamptz not null default now(),
  details_submitted_at timestamptz,
  paid_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.refund_requests enable row level security;
drop policy if exists refund_requests_participant_select on public.refund_requests;
create policy refund_requests_participant_select on public.refund_requests for select to authenticated
using (auth.uid() = buyer_id or auth.uid() = seller_id or public.has_role(auth.uid(),'admin'));
revoke insert, update, delete on public.refund_requests from authenticated, anon;
grant select on public.refund_requests to authenticated;
create index if not exists refund_requests_buyer_idx on public.refund_requests(buyer_id, status);
create index if not exists refund_requests_seller_idx on public.refund_requests(seller_id, status);
