-- ZXMAX: estoque e entrega por variação, com conteúdo automático privado.
-- O catálogo público guarda apenas metadados seguros. Códigos/itens de entrega
-- ficam em tabela privada e só são liberados ao pedido pago.

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS inventory_mode text NOT NULL DEFAULT 'legacy';

ALTER TABLE public.purchases
  ADD COLUMN IF NOT EXISTS variation_id text;

DO $$
BEGIN
  ALTER TABLE public.products
    ADD CONSTRAINT products_inventory_mode_check
    CHECK (inventory_mode IN ('legacy', 'items'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

GRANT SELECT (inventory_mode) ON public.products TO anon, authenticated;
GRANT INSERT (inventory_mode), UPDATE (inventory_mode) ON public.products TO authenticated;

CREATE TABLE IF NOT EXISTS public.product_inventory_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  variation_id text,
  seller_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content text NOT NULL,
  status text NOT NULL DEFAULT 'available',
  purchase_id bigint REFERENCES public.purchases(id) ON DELETE SET NULL,
  reserved_until timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  delivered_at timestamptz,
  CONSTRAINT product_inventory_items_content_check
    CHECK (char_length(btrim(content)) BETWEEN 1 AND 8000),
  CONSTRAINT product_inventory_items_status_check
    CHECK (status IN ('available', 'reserved', 'delivered'))
);

CREATE INDEX IF NOT EXISTS product_inventory_available_idx
  ON public.product_inventory_items(product_id, variation_id, status, id);

CREATE INDEX IF NOT EXISTS product_inventory_purchase_idx
  ON public.product_inventory_items(purchase_id)
  WHERE purchase_id IS NOT NULL;

ALTER TABLE public.product_inventory_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.product_inventory_items FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.product_inventory_items_id_seq FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.sync_product_inventory_stock(_product_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prod public.products%ROWTYPE;
  variation jsonb;
  next_variations jsonb := '[]'::jsonb;
  available_count integer;
  total_stock integer := 0;
  variation_stock integer;
  variation_id_value text;
  variation_delivery text;
BEGIN
  SELECT * INTO prod
  FROM public.products
  WHERE id = _product_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF jsonb_typeof(COALESCE(prod.variations, '[]'::jsonb)) = 'array'
     AND jsonb_array_length(COALESCE(prod.variations, '[]'::jsonb)) > 0 THEN
    FOR variation IN
      SELECT value FROM jsonb_array_elements(prod.variations)
    LOOP
      variation_id_value := NULLIF(btrim(variation->>'id'), '');
      variation_delivery := COALESCE(NULLIF(variation->>'deliveryType', ''), prod.delivery_type, 'manual');

      IF prod.inventory_mode = 'items'
         AND variation_delivery = 'auto'
         AND variation_id_value IS NOT NULL THEN
        SELECT count(*)::integer INTO available_count
        FROM public.product_inventory_items
        WHERE product_id = _product_id
          AND variation_id = variation_id_value
          AND status = 'available';

        variation := jsonb_set(variation, '{stock}', to_jsonb(available_count), true);
        variation_stock := available_count;
      ELSE
        variation_stock := CASE
          WHEN COALESCE(variation->>'stock', '') ~ '^\d+$'
            THEN GREATEST((variation->>'stock')::integer, 0)
          ELSE 0
        END;
      END IF;

      total_stock := total_stock + variation_stock;
      next_variations := next_variations || jsonb_build_array(variation);
    END LOOP;

    UPDATE public.products
    SET variations = next_variations,
        stock = total_stock,
        updated_at = now()
    WHERE id = _product_id;
  ELSIF prod.inventory_mode = 'items' AND prod.delivery_type = 'auto' THEN
    SELECT count(*)::integer INTO available_count
    FROM public.product_inventory_items
    WHERE product_id = _product_id
      AND variation_id IS NULL
      AND status = 'available';

    UPDATE public.products
    SET stock = available_count,
        updated_at = now()
    WHERE id = _product_id;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.sync_product_inventory_stock(bigint) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_product_auto_inventory(_product_id bigint)
RETURNS TABLE(item_id bigint, variation_id text, content text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prod public.products%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sessão expirada. Faça login novamente.';
  END IF;

  SELECT * INTO prod FROM public.products WHERE id = _product_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Produto não encontrado.';
  END IF;

  IF prod.seller_id <> auth.uid()
     AND NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'Sem permissão para gerenciar este estoque.';
  END IF;

  RETURN QUERY
  SELECT i.id, i.variation_id, i.content
  FROM public.product_inventory_items i
  WHERE i.product_id = _product_id
    AND i.status = 'available'
  ORDER BY i.variation_id NULLS FIRST, i.id;
END;
$$;

REVOKE ALL ON FUNCTION public.get_product_auto_inventory(bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_product_auto_inventory(bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.replace_product_auto_inventory(
  _product_id bigint,
  _inventories jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  prod public.products%ROWTYPE;
  cfg jsonb;
  item_text text;
  variation jsonb;
  requested_variation_id text;
  total_items integer := 0;
  inserted_items integer := 0;
  is_valid_target boolean;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Sessão expirada. Faça login novamente.';
  END IF;

  SELECT * INTO prod
  FROM public.products
  WHERE id = _product_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Produto não encontrado.';
  END IF;

  IF prod.seller_id <> auth.uid()
     AND NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'Sem permissão para gerenciar este estoque.';
  END IF;

  IF jsonb_typeof(COALESCE(_inventories, '[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'Configuração de estoque inválida.';
  END IF;

  -- Itens reservados/pagos são histórico do pedido e nunca são apagados por uma edição.
  DELETE FROM public.product_inventory_items
  WHERE product_id = _product_id
    AND status = 'available';

  FOR cfg IN SELECT value FROM jsonb_array_elements(COALESCE(_inventories, '[]'::jsonb))
  LOOP
    requested_variation_id := NULLIF(btrim(cfg->>'variationId'), '');
    is_valid_target := false;

    IF requested_variation_id IS NULL THEN
      is_valid_target :=
        jsonb_array_length(COALESCE(prod.variations, '[]'::jsonb)) = 0
        AND prod.delivery_type = 'auto';
    ELSE
      SELECT value INTO variation
      FROM jsonb_array_elements(COALESCE(prod.variations, '[]'::jsonb))
      WHERE value->>'id' = requested_variation_id
      LIMIT 1;

      is_valid_target :=
        variation IS NOT NULL
        AND COALESCE(NULLIF(variation->>'deliveryType', ''), prod.delivery_type) = 'auto';
    END IF;

    IF NOT is_valid_target THEN
      RAISE EXCEPTION 'Variação de entrega automática inválida.';
    END IF;

    IF jsonb_typeof(COALESCE(cfg->'items', '[]'::jsonb)) <> 'array' THEN
      RAISE EXCEPTION 'Lista de itens de entrega inválida.';
    END IF;

    FOR item_text IN
      SELECT DISTINCT btrim(value)
      FROM jsonb_array_elements_text(COALESCE(cfg->'items', '[]'::jsonb))
    LOOP
      IF item_text = '' THEN
        CONTINUE;
      END IF;
      IF char_length(item_text) > 8000 THEN
        RAISE EXCEPTION 'Um item de entrega ultrapassa o limite permitido.';
      END IF;

      total_items := total_items + 1;
      IF total_items > 5000 THEN
        RAISE EXCEPTION 'Limite de 5000 itens automáticos por anúncio.';
      END IF;

      INSERT INTO public.product_inventory_items(product_id, variation_id, seller_id, content)
      VALUES (_product_id, requested_variation_id, prod.seller_id, item_text);
      inserted_items := inserted_items + 1;
    END LOOP;
  END LOOP;

  PERFORM public.sync_product_inventory_stock(_product_id);

  RETURN jsonb_build_object(
    'success', true,
    'availableItems', inserted_items
  );
END;
$$;

REVOKE ALL ON FUNCTION public.replace_product_auto_inventory(bigint, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.replace_product_auto_inventory(bigint, jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.reserve_purchase_inventory(_purchase_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  purchase_row public.purchases%ROWTYPE;
  product_row public.products%ROWTYPE;
  variation jsonb;
  effective_delivery text;
  needed integer := 1;
  reserved_count integer := 0;
  had_expired boolean := false;
BEGIN
  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    RAISE EXCEPTION 'server_only';
  END IF;

  SELECT * INTO purchase_row
  FROM public.purchases
  WHERE id = _purchase_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'purchase_not_found';
  END IF;

  SELECT * INTO product_row
  FROM public.products
  WHERE id = purchase_row.product_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'product_not_found';
  END IF;

  IF purchase_row.variation_id IS NOT NULL OR purchase_row.variation_name IS NOT NULL THEN
    SELECT value INTO variation
    FROM jsonb_array_elements(COALESCE(product_row.variations, '[]'::jsonb))
    WHERE
      (purchase_row.variation_id IS NOT NULL AND value->>'id' = purchase_row.variation_id)
      OR
      (purchase_row.variation_id IS NULL AND purchase_row.variation_name IS NOT NULL AND value->>'name' = purchase_row.variation_name)
    LIMIT 1;
  END IF;

  effective_delivery := COALESCE(NULLIF(variation->>'deliveryType', ''), product_row.delivery_type, 'manual');

  IF product_row.inventory_mode <> 'items' OR effective_delivery <> 'auto' THEN
    RETURN jsonb_build_object('reserved', 0, 'mode', effective_delivery, 'inventoryMode', product_row.inventory_mode);
  END IF;

  -- Robux usa quantidade em unidades virtuais; o painel atual mantém Robux em entrega manual.
  -- Para qualquer outro produto, cada unidade comprada consome um item de estoque.
  IF product_row.category = 'Robux e Gift Cards' THEN
    needed := 1;
  ELSE
    needed := GREATEST(1, CEIL(COALESCE(purchase_row.quantity, 1))::integer);
  END IF;

  UPDATE public.product_inventory_items
  SET status = 'available',
      purchase_id = NULL,
      reserved_until = NULL
  WHERE product_id = product_row.id
    AND status = 'reserved'
    AND reserved_until IS NOT NULL
    AND reserved_until < now();

  GET DIAGNOSTICS reserved_count = ROW_COUNT;
  had_expired := reserved_count > 0;
  reserved_count := 0;

  WITH candidates AS (
    SELECT i.id
    FROM public.product_inventory_items i
    WHERE i.product_id = product_row.id
      AND i.status = 'available'
      AND (
        (purchase_row.variation_id IS NULL AND i.variation_id IS NULL)
        OR i.variation_id = purchase_row.variation_id
      )
    ORDER BY i.id
    FOR UPDATE SKIP LOCKED
    LIMIT needed
  ),
  claimed AS (
    UPDATE public.product_inventory_items i
    SET status = 'reserved',
        purchase_id = purchase_row.id,
        reserved_until = now() + interval '2 hours'
    FROM candidates c
    WHERE i.id = c.id
    RETURNING i.id
  )
  SELECT count(*)::integer INTO reserved_count FROM claimed;

  IF reserved_count <> needed THEN
    RAISE EXCEPTION 'automatic_stock_unavailable';
  END IF;

  PERFORM public.sync_product_inventory_stock(product_row.id);

  RETURN jsonb_build_object(
    'reserved', reserved_count,
    'needed', needed,
    'mode', 'auto',
    'expiresAt', now() + interval '2 hours',
    'reclaimedExpired', had_expired
  );
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_purchase_inventory(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.reserve_purchase_inventory(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.consume_purchase_inventory(_purchase_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  purchase_row public.purchases%ROWTYPE;
  product_row public.products%ROWTYPE;
  needed integer := 1;
  contents text;
BEGIN
  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    RAISE EXCEPTION 'server_only';
  END IF;

  SELECT * INTO purchase_row
  FROM public.purchases
  WHERE id = _purchase_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'purchase_not_found';
  END IF;

  SELECT * INTO product_row
  FROM public.products
  WHERE id = purchase_row.product_id
  FOR UPDATE;

  IF product_row.category <> 'Robux e Gift Cards' THEN
    needed := GREATEST(1, CEIL(COALESCE(purchase_row.quantity, 1))::integer);
  END IF;

  -- Caminho normal: consome exatamente o que foi reservado para este pedido.
  WITH consumed AS (
    UPDATE public.product_inventory_items
    SET status = 'delivered',
        delivered_at = now(),
        reserved_until = NULL
    WHERE purchase_id = _purchase_id
      AND status = 'reserved'
    RETURNING id, content
  )
  SELECT string_agg(content, E'\n' ORDER BY id) INTO contents
  FROM consumed;

  IF COALESCE(contents, '') <> '' THEN
    PERFORM public.sync_product_inventory_stock(product_row.id);
    RETURN contents;
  END IF;

  -- Fallback para pedidos criados antes da reserva: tenta consumir estoque disponível
  -- sem jamais entregar o mesmo item duas vezes.
  WITH candidates AS (
    SELECT i.id
    FROM public.product_inventory_items i
    WHERE i.product_id = product_row.id
      AND i.status = 'available'
      AND (
        (purchase_row.variation_id IS NULL AND i.variation_id IS NULL)
        OR i.variation_id = purchase_row.variation_id
      )
    ORDER BY i.id
    FOR UPDATE SKIP LOCKED
    LIMIT needed
  ),
  consumed AS (
    UPDATE public.product_inventory_items i
    SET status = 'delivered',
        purchase_id = _purchase_id,
        delivered_at = now(),
        reserved_until = NULL
    FROM candidates c
    WHERE i.id = c.id
    RETURNING i.id, i.content
  )
  SELECT string_agg(content, E'\n' ORDER BY id) INTO contents
  FROM consumed;

  PERFORM public.sync_product_inventory_stock(product_row.id);
  RETURN contents;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_purchase_inventory(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_purchase_inventory(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.decrement_purchase_manual_stock(_purchase_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.purchases%ROWTYPE;
  prod public.products%ROWTYPE;
  variation jsonb;
  next_variations jsonb := '[]'::jsonb;
  is_target boolean;
  current_stock integer;
  qty integer;
BEGIN
  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    RAISE EXCEPTION 'server_only';
  END IF;

  SELECT * INTO p FROM public.purchases WHERE id = _purchase_id FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;
  SELECT * INTO prod FROM public.products WHERE id = p.product_id FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;

  qty := CASE
    WHEN prod.category = 'Robux e Gift Cards'
      THEN GREATEST(1, CEIL(COALESCE(p.quantity, 1))::integer)
    ELSE GREATEST(1, CEIL(COALESCE(p.quantity, 1))::integer)
  END;

  IF jsonb_array_length(COALESCE(prod.variations, '[]'::jsonb)) > 0
     AND (p.variation_id IS NOT NULL OR (prod.category <> 'Robux e Gift Cards' AND p.variation_name IS NOT NULL)) THEN
    FOR variation IN SELECT value FROM jsonb_array_elements(prod.variations)
    LOOP
      is_target :=
        (p.variation_id IS NOT NULL AND variation->>'id' = p.variation_id)
        OR
        (p.variation_id IS NULL AND p.variation_name IS NOT NULL AND variation->>'name' = p.variation_name);

      IF is_target AND COALESCE(variation->>'stock', '') ~ '^\d+$' THEN
        current_stock := GREATEST((variation->>'stock')::integer - qty, 0);
        variation := jsonb_set(variation, '{stock}', to_jsonb(current_stock), true);
      END IF;
      next_variations := next_variations || jsonb_build_array(variation);
    END LOOP;

    UPDATE public.products
    SET variations = next_variations,
        stock = CASE WHEN stock IS NULL THEN NULL ELSE GREATEST(stock - qty, 0) END,
        updated_at = now()
    WHERE id = prod.id;
  ELSE
    UPDATE public.products
    SET stock = CASE WHEN stock IS NULL THEN NULL ELSE GREATEST(stock - qty, 0) END,
        updated_at = now()
    WHERE id = prod.id;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.decrement_purchase_manual_stock(bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.decrement_purchase_manual_stock(bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.apply_verified_payment_v2(
  _provider text,
  _event_key text,
  _event_type text,
  _purchase_id bigint,
  _charge_id text,
  _confirmed_amount numeric,
  _payload jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(applied boolean, resulting_status text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  purchase_row public.purchases%ROWTYPE;
  product_row public.products%ROWTYPE;
  variation jsonb;
  effective_delivery text;
  delivery_text text;
  next_status text := 'paid';
  next_messages jsonb;
  expected_charge text;
  settings jsonb := '{}'::jsonb;
  release_days integer := 7;
BEGIN
  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    RAISE EXCEPTION 'server_only';
  END IF;

  INSERT INTO public.payment_events(provider,event_key,event_type,purchase_id,charge_id,amount,payload)
  VALUES (_provider,_event_key,_event_type,_purchase_id,_charge_id,_confirmed_amount,COALESCE(_payload,'{}'::jsonb))
  ON CONFLICT (provider,event_key) DO NOTHING;

  IF NOT FOUND THEN
    SELECT p.status INTO resulting_status FROM public.purchases p WHERE p.id=_purchase_id;
    applied:=false; RETURN NEXT; RETURN;
  END IF;

  SELECT * INTO purchase_row FROM public.purchases WHERE id=_purchase_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'purchase_not_found'; END IF;
  IF purchase_row.status <> 'pending' THEN
    resulting_status:=purchase_row.status; applied:=false; RETURN NEXT; RETURN;
  END IF;

  expected_charge:=COALESCE(purchase_row.provider_payment_id,purchase_row.evopay_charge_id);
  IF expected_charge IS DISTINCT FROM _charge_id THEN RAISE EXCEPTION 'charge_mismatch'; END IF;
  IF round(purchase_row.amount*100) IS DISTINCT FROM round(_confirmed_amount*100) THEN RAISE EXCEPTION 'amount_mismatch'; END IF;

  SELECT * INTO product_row FROM public.products WHERE id=purchase_row.product_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'product_not_found'; END IF;

  IF purchase_row.variation_id IS NOT NULL OR purchase_row.variation_name IS NOT NULL THEN
    SELECT value INTO variation
    FROM jsonb_array_elements(COALESCE(product_row.variations, '[]'::jsonb))
    WHERE
      (purchase_row.variation_id IS NOT NULL AND value->>'id' = purchase_row.variation_id)
      OR
      (purchase_row.variation_id IS NULL AND purchase_row.variation_name IS NOT NULL AND value->>'name' = purchase_row.variation_name)
    LIMIT 1;
  END IF;

  effective_delivery := COALESCE(NULLIF(variation->>'deliveryType',''), product_row.delivery_type, 'manual');

  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  release_days:=GREATEST(5,LEAST(7,COALESCE((settings->>'seller_release_days')::integer,7)));
  next_messages:=COALESCE(purchase_row.messages,'[]'::jsonb);

  IF effective_delivery='auto' THEN
    IF product_row.inventory_mode='items' THEN
      delivery_text := public.consume_purchase_inventory(purchase_row.id);
    ELSE
      SELECT delivery_content INTO delivery_text
      FROM public.product_delivery
      WHERE product_id=purchase_row.product_id;
    END IF;

    IF COALESCE(delivery_text,'')<>'' THEN
      next_status:='delivered';
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object(
        'from','System',
        'text','📦 ENTREGA AUTOMÁTICA\n'||delivery_text,
        'date',now()
      ));
    ELSE
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object(
        'from','System',
        'text','⚠️ Pagamento confirmado, mas a entrega automática ficou sem item disponível. O vendedor foi mantido responsável pela entrega manual neste pedido.',
        'date',now()
      ));
      PERFORM public.decrement_purchase_manual_stock(purchase_row.id);
    END IF;
  ELSE
    PERFORM public.decrement_purchase_manual_stock(purchase_row.id);
  END IF;

  UPDATE public.purchases
  SET status=next_status,
      payment_status='paid',
      paid_at=COALESCE(paid_at,now()),
      funds_available_at=COALESCE(funds_available_at,now() + make_interval(days=>release_days)),
      seller_released=false,
      messages=next_messages,
      updated_at=now()
  WHERE id=_purchase_id;

  UPDATE public.products
  SET sales=COALESCE(sales,0)+1,
      updated_at=now()
  WHERE id=purchase_row.product_id;

  applied:=true; resulting_status:=next_status; RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_verified_payment(
  _provider text,
  _event_key text,
  _event_type text,
  _purchase_id bigint,
  _charge_id text,
  _confirmed_amount numeric,
  _payload jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE(applied boolean, resulting_status text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT * FROM public.apply_verified_payment_v2(
    _provider, _event_key, _event_type, _purchase_id, _charge_id, _confirmed_amount, _payload
  );
$$;

REVOKE ALL ON FUNCTION public.apply_verified_payment(text,text,text,bigint,text,numeric,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_verified_payment_v2(text,text,text,bigint,text,numeric,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_verified_payment(text,text,text,bigint,text,numeric,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_verified_payment_v2(text,text,text,bigint,text,numeric,jsonb) TO service_role;

CREATE OR REPLACE FUNCTION public.pay_purchase_with_wallet(_purchase_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.purchases%ROWTYPE;
  prod public.products%ROWTYPE;
  prof public.profiles%ROWTYPE;
  variation jsonb;
  effective_delivery text;
  bal numeric;
  delivery_text text;
  next_status text := 'paid';
  next_messages jsonb;
  settings jsonb := '{}'::jsonb;
  release_days integer := 7;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext(auth.uid()::text));

  SELECT * INTO prof FROM public.profiles WHERE user_id=auth.uid();
  IF prof IS NULL OR prof.verification_status <> 'approved' THEN
    RAISE EXCEPTION 'Verifique seus documentos antes de usar o saldo da carteira.';
  END IF;

  SELECT * INTO p FROM public.purchases WHERE id=_purchase_id FOR UPDATE;
  IF p IS NULL OR p.buyer_id<>auth.uid() THEN RAISE EXCEPTION 'Pedido não encontrado'; END IF;
  IF p.status<>'pending' THEN RAISE EXCEPTION 'Este pedido não está aguardando pagamento'; END IF;
  IF p.payment_provider<>'wallet' THEN RAISE EXCEPTION 'Forma de pagamento inválida'; END IF;

  bal:=public.wallet_available_balance(auth.uid());
  IF bal < p.amount THEN RAISE EXCEPTION 'Saldo da carteira insuficiente'; END IF;

  INSERT INTO public.wallet_ledger(user_id,amount,kind,purchase_id,description,dedupe_key)
  VALUES(auth.uid(),-p.amount,'purchase',p.id,'Compra do pedido #'||p.id,'wallet:purchase:'||p.id);

  SELECT * INTO prod FROM public.products WHERE id=p.product_id FOR UPDATE;
  IF prod IS NULL THEN RAISE EXCEPTION 'Produto indisponível'; END IF;

  IF p.variation_id IS NOT NULL OR p.variation_name IS NOT NULL THEN
    SELECT value INTO variation
    FROM jsonb_array_elements(COALESCE(prod.variations, '[]'::jsonb))
    WHERE
      (p.variation_id IS NOT NULL AND value->>'id'=p.variation_id)
      OR
      (p.variation_id IS NULL AND p.variation_name IS NOT NULL AND value->>'name'=p.variation_name)
    LIMIT 1;
  END IF;

  effective_delivery := COALESCE(NULLIF(variation->>'deliveryType',''), prod.delivery_type, 'manual');

  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  release_days:=GREATEST(5,LEAST(7,COALESCE((settings->>'seller_release_days')::integer,7)));
  next_messages:=COALESCE(p.messages,'[]'::jsonb);

  IF effective_delivery='auto' THEN
    IF prod.inventory_mode='items' THEN
      delivery_text:=public.consume_purchase_inventory(p.id);
    ELSE
      SELECT delivery_content INTO delivery_text
      FROM public.product_delivery
      WHERE product_id=p.product_id;
    END IF;

    IF COALESCE(delivery_text,'')<>'' THEN
      next_status:='delivered';
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object(
        'from','System',
        'text','📦 ENTREGA AUTOMÁTICA\n'||delivery_text,
        'date',now()
      ));
    ELSE
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object(
        'from','System',
        'text','⚠️ Pagamento confirmado, mas a entrega automática ficou sem item disponível. O vendedor deve concluir a entrega manualmente.',
        'date',now()
      ));
      PERFORM public.decrement_purchase_manual_stock(p.id);
    END IF;
  ELSE
    PERFORM public.decrement_purchase_manual_stock(p.id);
  END IF;

  UPDATE public.purchases
  SET status=next_status,
      payment_status='paid',
      provider_payment_id='wallet:'||p.id,
      paid_at=now(),
      funds_available_at=now()+make_interval(days=>release_days),
      seller_released=false,
      messages=next_messages,
      updated_at=now()
  WHERE id=p.id;

  UPDATE public.products
  SET sales=COALESCE(sales,0)+1,
      updated_at=now()
  WHERE id=p.product_id;

  RETURN jsonb_build_object('success',true,'status',next_status,'balance',public.wallet_available_balance(auth.uid()));
END;
$$;

-- A view pública continua sem conteúdo de entrega.
CREATE OR REPLACE VIEW public.products_public
WITH (security_invoker = true)
AS
SELECT
  id,
  seller_id,
  seller_public_id,
  seller_name,
  name,
  price,
  category,
  image,
  banner,
  description,
  approved,
  delivery_type,
  variations,
  questions,
  sales,
  rating,
  created_at,
  updated_at,
  stock,
  min_quantity,
  delivery_time,
  review_count,
  review_avg,
  review_positive,
  inventory_mode
FROM public.products
WHERE approved = true;

REVOKE ALL ON public.products_public FROM anon, authenticated;
GRANT SELECT ON public.products_public TO anon, authenticated;

COMMENT ON TABLE public.product_inventory_items IS
  'Itens secretos de entrega automática. Nunca expor no catálogo público.';
