-- ZXMAX · destinos pessoais de Discord por evento.
-- A URL de webhook é um segredo operacional: fica no Vault e nunca em tabela
-- exposta, resposta de cliente ou registro de entrega.

CREATE EXTENSION IF NOT EXISTS supabase_vault WITH SCHEMA vault;

CREATE TABLE IF NOT EXISTS public.user_discord_webhooks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('sale_confirmed', 'product_question', 'product_review')),
  vault_secret_id uuid NOT NULL UNIQUE,
  active boolean NOT NULL DEFAULT true,
  last_delivery_status text NOT NULL DEFAULT 'not_sent'
    CHECK (last_delivery_status IN ('not_sent', 'sent', 'rate_limited', 'disabled_not_found', 'failed')),
  last_delivery_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, event_type)
);

CREATE TABLE IF NOT EXISTS public.discord_webhook_delivery_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_id uuid REFERENCES public.user_discord_webhooks(id) ON DELETE SET NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (event_type IN ('sale_confirmed', 'product_question', 'product_review')),
  event_key text NOT NULL CHECK (char_length(event_key) BETWEEN 8 AND 220),
  status text NOT NULL CHECK (status IN ('claimed', 'sent', 'rate_limited', 'disabled_not_found', 'failed')),
  provider_status integer CHECK (provider_status BETWEEN 100 AND 599),
  retry_after_seconds numeric(12,3) CHECK (retry_after_seconds IS NULL OR retry_after_seconds >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (webhook_id, event_key)
);

CREATE INDEX IF NOT EXISTS user_discord_webhooks_owner_idx
  ON public.user_discord_webhooks(user_id, event_type);
CREATE INDEX IF NOT EXISTS discord_webhook_delivery_owner_idx
  ON public.discord_webhook_delivery_log(user_id, event_type, created_at DESC);

ALTER TABLE public.user_discord_webhooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_webhook_delivery_log ENABLE ROW LEVEL SECURITY;

-- Deny by default: the Edge Functions return a deliberately small public shape.
REVOKE ALL ON TABLE public.user_discord_webhooks FROM anon, authenticated;
REVOKE ALL ON TABLE public.discord_webhook_delivery_log FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.set_user_discord_webhook_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS user_discord_webhooks_updated_at ON public.user_discord_webhooks;
CREATE TRIGGER user_discord_webhooks_updated_at
  BEFORE UPDATE ON public.user_discord_webhooks
  FOR EACH ROW EXECUTE FUNCTION public.set_user_discord_webhook_updated_at();

CREATE OR REPLACE FUNCTION public.is_valid_discord_webhook_url(_url text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT coalesce(_url, '') ~ '^https://(?:(?:canary|ptb)\.)?discord(?:app)?\.com/api(?:/v[0-9]+)?/webhooks/[0-9]{17,20}/[A-Za-z0-9._-]{20,200}$';
$$;

-- Called only by the authenticated Edge Function with the user determined from
-- its JWT. The function itself is not executable by normal database roles.
CREATE OR REPLACE FUNCTION public.manage_user_discord_webhook_internal(
  _user_id uuid,
  _event_type text,
  _action text,
  _webhook_url text DEFAULT NULL,
  _active boolean DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, vault
AS $$
DECLARE
  existing public.user_discord_webhooks;
  secret_id uuid;
  normalized_url text := btrim(coalesce(_webhook_url, ''));
BEGIN
  IF _user_id IS NULL THEN
    RAISE EXCEPTION 'Sessão inválida.' USING ERRCODE = '42501';
  END IF;
  IF _event_type NOT IN ('sale_confirmed', 'product_question', 'product_review') THEN
    RAISE EXCEPTION 'Evento de integração inválido.' USING ERRCODE = '22023';
  END IF;
  IF _action NOT IN ('set', 'toggle', 'remove') THEN
    RAISE EXCEPTION 'Ação de integração inválida.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO existing
    FROM public.user_discord_webhooks
   WHERE user_id = _user_id AND event_type = _event_type
   FOR UPDATE;

  IF _action = 'set' THEN
    IF NOT public.is_valid_discord_webhook_url(normalized_url) THEN
      RAISE EXCEPTION 'URL de webhook Discord inválida.' USING ERRCODE = '22023';
    END IF;
    IF existing.id IS NULL THEN
      SELECT vault.create_secret(normalized_url) INTO secret_id;
      INSERT INTO public.user_discord_webhooks(user_id, event_type, vault_secret_id, active, last_delivery_status)
      VALUES (_user_id, _event_type, secret_id, true, 'not_sent')
      RETURNING * INTO existing;
    ELSE
      PERFORM vault.update_secret(existing.vault_secret_id, normalized_url, NULL, NULL);
      UPDATE public.user_discord_webhooks
         SET active = true,
             last_delivery_status = 'not_sent',
             last_delivery_at = NULL
       WHERE id = existing.id
       RETURNING * INTO existing;
    END IF;
  ELSIF _action = 'toggle' THEN
    IF existing.id IS NULL OR _active IS NULL THEN
      RAISE EXCEPTION 'Destino de integração não encontrado.' USING ERRCODE = 'P0002';
    END IF;
    UPDATE public.user_discord_webhooks
       SET active = _active
     WHERE id = existing.id
     RETURNING * INTO existing;
  ELSE
    IF existing.id IS NULL THEN
      RETURN jsonb_build_object('removed', false, 'event_type', _event_type);
    END IF;
    DELETE FROM public.user_discord_webhooks WHERE id = existing.id;
    DELETE FROM vault.secrets WHERE id = existing.vault_secret_id;
    RETURN jsonb_build_object('removed', true, 'event_type', _event_type);
  END IF;

  RETURN jsonb_build_object(
    'event_type', existing.event_type,
    'active', existing.active,
    'last_delivery_status', existing.last_delivery_status,
    'last_delivery_at', existing.last_delivery_at,
    'updated_at', existing.updated_at
  );
END;
$$;

-- The decrypted value is returned only to service_role for server-side delivery.
CREATE OR REPLACE FUNCTION public.get_user_discord_webhook_delivery_target(
  _user_id uuid,
  _event_type text
)
RETURNS TABLE(webhook_id uuid, webhook_url text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, vault
AS $$
  SELECT w.id, d.decrypted_secret
    FROM public.user_discord_webhooks w
    JOIN vault.decrypted_secrets d ON d.id = w.vault_secret_id
   WHERE w.user_id = _user_id
     AND w.event_type = _event_type
     AND w.active = true
   LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.claim_user_discord_webhook_delivery(
  _webhook_id uuid,
  _user_id uuid,
  _event_type text,
  _event_key text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF _webhook_id IS NULL OR _user_id IS NULL
     OR _event_type NOT IN ('sale_confirmed', 'product_question', 'product_review')
     OR char_length(coalesce(_event_key, '')) NOT BETWEEN 8 AND 220 THEN
    RAISE EXCEPTION 'Entrega de integração inválida.' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.discord_webhook_delivery_log(webhook_id, user_id, event_type, event_key, status)
  VALUES (_webhook_id, _user_id, _event_type, _event_key, 'claimed')
  ON CONFLICT (webhook_id, event_key) DO NOTHING;
  RETURN FOUND;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_user_discord_webhook_delivery(
  _webhook_id uuid,
  _event_key text,
  _status text,
  _provider_status integer DEFAULT NULL,
  _retry_after_seconds numeric DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  owner_id uuid;
BEGIN
  IF _status NOT IN ('sent', 'rate_limited', 'disabled_not_found', 'failed') THEN
    RAISE EXCEPTION 'Estado de entrega inválido.' USING ERRCODE = '22023';
  END IF;

  UPDATE public.discord_webhook_delivery_log
     SET status = _status,
         provider_status = _provider_status,
         retry_after_seconds = CASE WHEN _status = 'rate_limited' THEN _retry_after_seconds ELSE NULL END,
         completed_at = now()
   WHERE webhook_id = _webhook_id
     AND event_key = _event_key
   RETURNING user_id INTO owner_id;

  IF owner_id IS NULL THEN
    RAISE EXCEPTION 'Entrega de integração não encontrada.' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.user_discord_webhooks
     SET active = CASE WHEN _status = 'disabled_not_found' THEN false ELSE active END,
         last_delivery_status = _status,
         last_delivery_at = now()
   WHERE id = _webhook_id;
END;
$$;

REVOKE ALL ON FUNCTION public.is_valid_discord_webhook_url(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.manage_user_discord_webhook_internal(uuid, text, text, text, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_user_discord_webhook_delivery_target(uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.claim_user_discord_webhook_delivery(uuid, uuid, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_user_discord_webhook_delivery(uuid, text, text, integer, numeric) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.manage_user_discord_webhook_internal(uuid, text, text, text, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_user_discord_webhook_delivery_target(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_user_discord_webhook_delivery(uuid, uuid, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_user_discord_webhook_delivery(uuid, text, text, integer, numeric) TO service_role;
