
ALTER TABLE public.withdrawals
  ADD COLUMN IF NOT EXISTS idempotency_key text,
  ADD COLUMN IF NOT EXISTS provider_tx_id text,
  ADD COLUMN IF NOT EXISTS rejection_reason text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS processed_at timestamptz,
  ADD COLUMN IF NOT EXISTS retry_of bigint REFERENCES public.withdrawals(id) ON DELETE SET NULL;

UPDATE public.withdrawals SET idempotency_key = 'legacy_' || id::text WHERE idempotency_key IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS withdrawals_idempotency_key_uidx ON public.withdrawals(idempotency_key);

CREATE TABLE IF NOT EXISTS public.withdrawal_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  withdrawal_id bigint NOT NULL REFERENCES public.withdrawals(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  actor_id uuid,
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.withdrawal_events TO authenticated;
GRANT ALL ON public.withdrawal_events TO service_role;
ALTER TABLE public.withdrawal_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner and admins can view withdrawal events" ON public.withdrawal_events;
CREATE POLICY "Owner and admins can view withdrawal events"
ON public.withdrawal_events FOR SELECT TO authenticated
USING (
  public.has_role(auth.uid(), 'admin')
  OR EXISTS (SELECT 1 FROM public.withdrawals w WHERE w.id = withdrawal_id AND w.user_id = auth.uid())
);

CREATE INDEX IF NOT EXISTS idx_withdrawal_events_withdrawal ON public.withdrawal_events(withdrawal_id);

-- Available balance helper (same rule used by validate_withdrawal)
CREATE OR REPLACE FUNCTION public.withdrawable_balance(_user_id uuid, _exclude_id bigint DEFAULT NULL)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  commission numeric := 10;
  gross numeric := 0;
  already numeric := 0;
BEGIN
  SELECT COALESCE((value->>'commission')::numeric, 10) INTO commission
  FROM public.app_settings WHERE key = 'fees';
  commission := COALESCE(commission, 10);

  SELECT COALESCE(SUM(amount), 0) INTO gross
  FROM public.purchases
  WHERE seller_id = _user_id AND status = 'delivered';

  SELECT COALESCE(SUM(amount), 0) INTO already
  FROM public.withdrawals
  WHERE user_id = _user_id
    AND status IN ('pending', 'approved')
    AND (_exclude_id IS NULL OR id <> _exclude_id);

  RETURN ROUND((gross * (100 - commission) / 100) - already, 2);
END;
$$;

REVOKE ALL ON FUNCTION public.withdrawable_balance(uuid, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.withdrawable_balance(uuid, bigint) TO authenticated, service_role;

-- Approve: idempotent, revalidates balance, locks the row
CREATE OR REPLACE FUNCTION public.approve_withdrawal(_id bigint, _provider_tx text DEFAULT NULL)
RETURNS public.withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  w public.withdrawals;
  available numeric;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Apenas administradores podem aprovar saques';
  END IF;

  SELECT * INTO w FROM public.withdrawals WHERE id = _id FOR UPDATE;
  IF w IS NULL THEN RAISE EXCEPTION 'Saque não encontrado'; END IF;

  IF w.status = 'approved' THEN
    RETURN w; -- idempotent
  END IF;
  IF w.status <> 'pending' THEN
    RAISE EXCEPTION 'Saque já foi % e não pode ser aprovado', w.status;
  END IF;

  available := public.withdrawable_balance(w.user_id, w.id);
  IF w.amount > available THEN
    RAISE EXCEPTION 'Saldo insuficiente no momento da aprovação. Disponível: R$ %', available;
  END IF;

  UPDATE public.withdrawals
     SET status = 'approved',
         provider_tx_id = COALESCE(_provider_tx, provider_tx_id),
         processed_at = now()
   WHERE id = _id
   RETURNING * INTO w;

  INSERT INTO public.withdrawal_events (withdrawal_id, event_type, actor_id, note)
  VALUES (_id, 'approved', auth.uid(), COALESCE(_provider_tx, ''));

  RETURN w;
END;
$$;

REVOKE ALL ON FUNCTION public.approve_withdrawal(bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.approve_withdrawal(bigint, text) TO authenticated, service_role;

-- Reject with reason
CREATE OR REPLACE FUNCTION public.reject_withdrawal(_id bigint, _reason text DEFAULT '')
RETURNS public.withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  w public.withdrawals;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin') THEN
    RAISE EXCEPTION 'Apenas administradores podem recusar saques';
  END IF;

  SELECT * INTO w FROM public.withdrawals WHERE id = _id FOR UPDATE;
  IF w IS NULL THEN RAISE EXCEPTION 'Saque não encontrado'; END IF;
  IF w.status = 'rejected' THEN RETURN w; END IF;
  IF w.status <> 'pending' THEN
    RAISE EXCEPTION 'Saque já foi % e não pode ser recusado', w.status;
  END IF;

  UPDATE public.withdrawals
     SET status = 'rejected',
         rejection_reason = COALESCE(NULLIF(TRIM(_reason), ''), 'Não informado'),
         processed_at = now()
   WHERE id = _id
   RETURNING * INTO w;

  INSERT INTO public.withdrawal_events (withdrawal_id, event_type, actor_id, note)
  VALUES (_id, 'rejected', auth.uid(), COALESCE(_reason, ''));

  RETURN w;
END;
$$;

REVOKE ALL ON FUNCTION public.reject_withdrawal(bigint, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reject_withdrawal(bigint, text) TO authenticated, service_role;

-- Request (idempotent) and resubmit after rejection
CREATE OR REPLACE FUNCTION public.request_withdrawal(
  _amount numeric,
  _method text DEFAULT 'normal',
  _idempotency_key text DEFAULT NULL,
  _retry_of bigint DEFAULT NULL
)
RETURNS public.withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  w public.withdrawals;
  prof public.profiles;
  key text := COALESCE(NULLIF(TRIM(_idempotency_key), ''), gen_random_uuid()::text);
  prev public.withdrawals;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF;

  SELECT * INTO w FROM public.withdrawals WHERE idempotency_key = key;
  IF w IS NOT NULL THEN
    IF w.user_id <> auth.uid() THEN RAISE EXCEPTION 'Chave de idempotência inválida'; END IF;
    RETURN w; -- idempotent replay
  END IF;

  SELECT * INTO prof FROM public.profiles WHERE user_id = auth.uid();
  IF prof IS NULL THEN RAISE EXCEPTION 'Perfil não encontrado'; END IF;
  IF NOT prof.is_verified_seller THEN
    RAISE EXCEPTION 'Conclua a verificação de identidade antes de sacar';
  END IF;

  IF _retry_of IS NOT NULL THEN
    SELECT * INTO prev FROM public.withdrawals WHERE id = _retry_of FOR UPDATE;
    IF prev IS NULL OR prev.user_id <> auth.uid() THEN
      RAISE EXCEPTION 'Saque original não encontrado';
    END IF;
    IF prev.status <> 'rejected' THEN
      RAISE EXCEPTION 'Só é possível reenviar um saque recusado';
    END IF;
  END IF;

  INSERT INTO public.withdrawals (user_id, user_public_id, user_email, amount, method, pix_key, idempotency_key, retry_of)
  VALUES (auth.uid(), prof.public_id::text, prof.email, ROUND(_amount, 2), COALESCE(_method, 'normal'),
          COALESCE(prof.pix_key, ''), key, _retry_of)
  RETURNING * INTO w;

  INSERT INTO public.withdrawal_events (withdrawal_id, event_type, actor_id, note)
  VALUES (w.id, CASE WHEN _retry_of IS NULL THEN 'requested' ELSE 'resubmitted' END, auth.uid(), '');

  RETURN w;
END;
$$;

REVOKE ALL ON FUNCTION public.request_withdrawal(numeric, text, text, bigint) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(numeric, text, text, bigint) TO authenticated, service_role;
