create table if not exists public.merchant_charges (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  amount numeric(12,2) not null check (amount >= 2 and amount <= 5000),
  description text not null check (char_length(description) between 4 and 120),
  provider text not null default 'magnuspay',
  provider_payment_id text unique,
  provider_amount numeric(12,2),
  provider_fee numeric(12,2),
  provider_net_amount numeric(12,2),
  pix_qr_code text,
  status text not null default 'creating' check (status in ('creating','pending','paid','expired','failed','cancelled')),
  expires_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.merchant_charges enable row level security;

drop policy if exists merchant_charges_select_own on public.merchant_charges;
create policy merchant_charges_select_own
on public.merchant_charges for select
to authenticated
using (owner_id = auth.uid());

revoke all on public.merchant_charges from anon;
grant select on public.merchant_charges to authenticated;

create or replace function public.get_my_app_dashboard()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid := auth.uid();
  prof public.profiles%rowtype;
  result jsonb;
begin
  if uid is null then raise exception 'Não autenticado' using errcode='42501'; end if;
  select * into prof from public.profiles where user_id=uid limit 1;
  if prof is null then raise exception 'Perfil não encontrado' using errcode='42501'; end if;

  select jsonb_build_object(
    'balance', public.wallet_available_balance(uid),
    'salesCount', (select count(*) from public.purchases where seller_id=uid and status in ('paid','delivered_pending_confirmation','delivered')),
    'salesValue', (select coalesce(sum(coalesce(product_amount,greatest(amount-coalesce(buyer_fee,0),0))),0) from public.purchases where seller_id=uid and status in ('paid','delivered_pending_confirmation','delivered')),
    'pendingOrders', (select count(*) from public.purchases where seller_id=uid and status in ('paid','delivered_pending_confirmation')),
    'messageCount', (select count(*) from public.order_messages om join public.purchases p on p.id=om.order_id where p.seller_id=uid or p.buyer_id=uid),
    'questionCount', (select count(*) from public.product_questions q join public.products p on p.id=q.product_id where p.seller_id=uid and q.answer is null),
    'activeListings', (select count(*) from public.products where seller_id=uid and approved=true),
    'documentVerified', prof.verification_status='approved',
    'recentSales', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',x.id,'amount',x.amount,'status',x.status,'createdAt',x.created_at,'buyerPublicId',x.buyer_public_id
      ) order by x.created_at desc)
      from (
        select id,amount,status,created_at,buyer_public_id
        from public.purchases
        where seller_id=uid
        order by created_at desc
        limit 10
      ) x
    ),'[]'::jsonb),
    'ledger', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',x.id,'amount',x.amount,'kind',x.kind,'description',x.description,'createdAt',x.created_at,'availableAt',x.available_at
      ) order by x.created_at desc)
      from (
        select id,amount,kind,description,created_at,available_at
        from public.wallet_ledger
        where user_id=uid
        order by created_at desc
        limit 30
      ) x
    ),'[]'::jsonb),
    'withdrawals', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',x.id,'amount',x.amount,'fee',x.fee,'netAmount',x.net_amount,'status',x.status,'createdAt',x.created_at
      ) order by x.created_at desc)
      from (
        select id,amount,fee,net_amount,status,created_at
        from public.withdrawals
        where user_id=uid
        order by created_at desc
        limit 15
      ) x
    ),'[]'::jsonb),
    'charges', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',x.id,'amount',x.amount,'providerAmount',x.provider_amount,'providerNetAmount',x.provider_net_amount,
        'description',x.description,'status',x.status,'qrCode',x.pix_qr_code,'createdAt',x.created_at,'expiresAt',x.expires_at
      ) order by x.created_at desc)
      from (
        select id,amount,provider_amount,provider_net_amount,description,status,pix_qr_code,created_at,expires_at
        from public.merchant_charges
        where owner_id=uid
        order by created_at desc
        limit 20
      ) x
    ),'[]'::jsonb)
  ) into result;
  return result;
end;
$$;

create or replace function public.get_admin_financial_activity(_limit integer default 200)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  lim integer := greatest(1,least(coalesce(_limit,200),500));
begin
  if auth.uid() is null or not public.has_role(auth.uid(),'admin'::public.app_role) then
    raise exception 'Apenas administradores.' using errcode='42501';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(x) order by x."occurredAt" desc)
    from (
      select * from (
        select
          'wallet'::text as type,
          wl.id::text as id,
          pr.public_id::text as "publicId",
          pr.display_name as "userName",
          pr.email as "userEmail",
          wl.amount::numeric as amount,
          wl.kind as status,
          wl.description,
          wl.created_at as "occurredAt"
        from public.wallet_ledger wl
        join public.profiles pr on pr.user_id=wl.user_id

        union all

        select
          'withdrawal', w.id::text, w.user_public_id, coalesce(pr.display_name,'Usuário'), w.user_email,
          -w.amount, w.status, 'Saque · taxa '||coalesce(w.fee,0)::text, w.created_at
        from public.withdrawals w
        left join public.profiles pr on pr.user_id=w.user_id

        union all

        select
          'purchase', p.id::text, p.buyer_public_id, coalesce(pr.display_name,'Comprador'), p.buyer_email,
          p.amount, p.payment_status, 'Pedido #'||p.id::text, p.created_at
        from public.purchases p
        left join public.profiles pr on pr.user_id=p.buyer_id

        union all

        select
          'charge', c.id::text, pr.public_id::text, pr.display_name, pr.email,
          c.amount, c.status, c.description, c.created_at
        from public.merchant_charges c
        join public.profiles pr on pr.user_id=c.owner_id
      ) u
      order by "occurredAt" desc
      limit lim
    ) x
  ),'[]'::jsonb);
end;
$$;

create or replace function public.admin_adjust_wallet_balance(_public_id bigint,_amount numeric,_reason text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  target public.profiles%rowtype;
  clean_amount numeric := round(coalesce(_amount,0),2);
  clean_reason text := btrim(coalesce(_reason,''));
  current_balance numeric := 0;
  ledger_id bigint;
begin
  if auth.uid() is null or not public.has_role(auth.uid(),'admin'::public.app_role) then
    raise exception 'Apenas administradores.' using errcode='42501';
  end if;
  if clean_amount=0 or abs(clean_amount)>1000000 then raise exception 'Valor de ajuste inválido'; end if;
  if char_length(clean_reason)<8 or char_length(clean_reason)>300 then raise exception 'Motivo deve ter de 8 a 300 caracteres'; end if;

  select * into target from public.profiles where public_id=_public_id limit 1;
  if target is null then raise exception 'Usuário não encontrado'; end if;

  perform pg_advisory_xact_lock(hashtext(target.user_id::text));
  current_balance := public.wallet_available_balance(target.user_id);
  if clean_amount<0 and abs(clean_amount)>current_balance then
    raise exception 'Débito maior que o saldo disponível';
  end if;

  insert into public.wallet_ledger(user_id,amount,kind,purchase_id,description,dedupe_key,available_at)
  values(
    target.user_id,clean_amount,'admin_adjustment',null,
    case when clean_amount<0 then 'Débito administrativo: ' else 'Crédito administrativo: ' end || clean_reason,
    'admin_adjustment:'||gen_random_uuid()::text,now()
  )
  returning id into ledger_id;

  insert into public.admin_audit_log(actor_id,action,target_table,target_id,reason,metadata)
  values(
    auth.uid(),'wallet.admin_adjustment','wallet_ledger',ledger_id::text,clean_reason,
    jsonb_build_object('publicId',_public_id,'amount',clean_amount,'previousBalance',current_balance)
  );

  return jsonb_build_object(
    'success',true,'ledgerId',ledger_id,
    'newBalance',public.wallet_available_balance(target.user_id)
  );
end;
$$;

grant execute on function public.get_my_app_dashboard() to authenticated;
grant execute on function public.get_admin_financial_activity(integer) to authenticated;
grant execute on function public.admin_adjust_wallet_balance(bigint,numeric,text) to authenticated;
