-- ============================================================================
-- ZXMAX · Avaliações reais de compradores (persistidas e moderadas no servidor)
-- ============================================================================
-- O comprador avalia APÓS confirmar o recebimento; a verificação de posse do
-- pedido e o bloqueio de contato externo vivem no banco, nunca na interface.

-- 1) Colunas agregadas em products (atualizadas por trigger)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS review_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS review_avg numeric(3,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS review_positive integer NOT NULL DEFAULT 0;

GRANT SELECT (review_count, review_avg, review_positive) ON public.products TO anon, authenticated;

-- 2) Tabela de avaliações
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  seller_id uuid NOT NULL,
  buyer_id uuid NOT NULL,
  purchase_id bigint NOT NULL,
  stars smallint NOT NULL CHECK (stars BETWEEN 1 AND 5),
  comment text NOT NULL CHECK (char_length(btrim(comment)) BETWEEN 3 AND 1000),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS product_reviews_product_idx ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS product_reviews_seller_idx ON public.product_reviews(seller_id);
CREATE UNIQUE INDEX IF NOT EXISTS product_reviews_purchase_uidx ON public.product_reviews(purchase_id);

ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can read product reviews" ON public.product_reviews;
CREATE POLICY "Anyone can read product reviews"
  ON public.product_reviews FOR SELECT USING (true);

-- Inserts go only through the RPC below (binds buyer to auth.uid() + ownership).
REVOKE INSERT, UPDATE, DELETE ON public.product_reviews FROM anon, authenticated;
GRANT SELECT ON public.product_reviews TO anon, authenticated;

-- 3) Manutenção dos agregados em products
CREATE OR REPLACE FUNCTION public.refresh_product_review_stats(_product_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  cnt int;
  avg_val numeric;
  pos int;
BEGIN
  SELECT count(*), coalesce(avg(stars), 0), count(*) FILTER (WHERE stars >= 4)
    INTO cnt, avg_val, pos
    FROM public.product_reviews
   WHERE product_id = _product_id;
  UPDATE public.products
     SET review_count = cnt,
         review_avg = avg_val,
         review_positive = pos
   WHERE id = _product_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.maintain_product_review_stats()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_product_review_stats(OLD.product_id);
    RETURN OLD;
  ELSE
    PERFORM public.refresh_product_review_stats(NEW.product_id);
    RETURN NEW;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS maintain_product_review_stats_trg ON public.product_reviews;
CREATE TRIGGER maintain_product_review_stats_trg
  AFTER INSERT OR UPDATE OR DELETE ON public.product_reviews
  FOR EACH ROW EXECUTE FUNCTION public.maintain_product_review_stats();

-- 4) RPC: cria avaliação (comprador dono do pedido, já entregue, 1 por pedido)
CREATE OR REPLACE FUNCTION public.create_product_review(_purchase_id bigint, _stars int, _comment text)
RETURNS public.product_reviews
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_purchase public.purchases;
  clean_comment text := btrim(coalesce(_comment, ''));
  created_review public.product_reviews;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Faça login para avaliar.' USING ERRCODE = '42501';
  END IF;
  IF _stars IS NULL OR _stars < 1 OR _stars > 5 THEN
    RAISE EXCEPTION 'A avaliação deve ter entre 1 e 5 estrelas.' USING ERRCODE = '22023';
  END IF;
  IF char_length(clean_comment) < 3 OR char_length(clean_comment) > 1000 THEN
    RAISE EXCEPTION 'O comentário deve ter entre 3 e 1000 caracteres.' USING ERRCODE = '22023';
  END IF;

  -- Bloqueio de contato externo também no servidor (WhatsApp, Discord, e-mail, links, telefone)
  PERFORM public.reject_external_contact(clean_comment);

  SELECT * INTO v_purchase FROM public.purchases WHERE id = _purchase_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pedido não encontrado.' USING ERRCODE = 'P0002';
  END IF;
  IF v_purchase.buyer_id <> auth.uid() THEN
    RAISE EXCEPTION 'Apenas o comprador pode avaliar este pedido.' USING ERRCODE = '42501';
  END IF;
  IF v_purchase.status NOT IN ('delivered', 'delivered_pending_confirmation') THEN
    RAISE EXCEPTION 'Só é possível avaliar após a confirmação do recebimento.' USING ERRCODE = 'P0001';
  END IF;
  IF EXISTS (SELECT 1 FROM public.product_reviews WHERE purchase_id = _purchase_id) THEN
    RAISE EXCEPTION 'Você já avaliou este pedido.' USING ERRCODE = '23505';
  END IF;

  INSERT INTO public.product_reviews (product_id, seller_id, buyer_id, purchase_id, stars, comment)
  VALUES (v_purchase.product_id, v_purchase.seller_id, auth.uid(), _purchase_id, _stars, clean_comment)
  RETURNING * INTO created_review;

  RETURN created_review;
END;
$$;

REVOKE ALL ON FUNCTION public.create_product_review(bigint, int, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_product_review(bigint, int, text) TO authenticated, service_role;

-- 5) Expor os agregados na view pública (leitura anônima das avaliações)
DROP VIEW IF EXISTS public.products_public;
CREATE VIEW public.products_public
WITH (security_invoker = true) AS
SELECT
  id,
  seller_id,
  seller_public_id,
  seller_name,
  name,
  price,
  category,
  image,
  banner,
  description,
  approved,
  delivery_type,
  variations,
  questions,
  sales,
  rating,
  created_at,
  updated_at,
  stock,
  min_quantity,
  delivery_time,
  review_count,
  review_avg,
  review_positive
FROM public.products
WHERE approved = true;

GRANT SELECT ON public.products_public TO anon, authenticated, service_role;
