-- ZXMAX marketplace hardening: notifications, verification, wallet holds and withdrawal rules.

-- 1) Verification state -------------------------------------------------------
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS phone_verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS verification_rg_front_path text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS verification_rg_back_path text NOT NULL DEFAULT '';

-- Public profile exposes only boolean trust signals, never private document data.
CREATE OR REPLACE VIEW public.profiles_public
WITH (security_invoker = on) AS
SELECT
  user_id,
  public_id,
  display_name,
  avatar_url,
  is_verified_seller,
  created_at,
  (phone_verified_at IS NOT NULL) AS phone_verified,
  (verification_status = 'approved') AS document_verified
FROM public.profiles;

GRANT SELECT ON public.profiles_public TO anon, authenticated;
GRANT ALL ON public.profiles_public TO service_role;

-- Creating a listing requires a verified phone number. Admin/service operations
-- remain possible so moderation/import tools are not blocked.
CREATE OR REPLACE FUNCTION public.enforce_listing_phone_verification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  verified_at timestamptz;
BEGIN
  IF current_user IN ('postgres','service_role','supabase_admin') THEN
    RETURN NEW;
  END IF;
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Faça login para anunciar.' USING ERRCODE = '42501';
  END IF;
  IF public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RETURN NEW;
  END IF;
  SELECT phone_verified_at INTO verified_at
  FROM public.profiles
  WHERE user_id = auth.uid();
  IF verified_at IS NULL THEN
    RAISE EXCEPTION 'Verifique seu número por SMS antes de anunciar.' USING ERRCODE = '42501';
  END IF;
  IF NEW.seller_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Vendedor inválido.' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enforce_listing_phone_verification_trg ON public.products;
CREATE TRIGGER enforce_listing_phone_verification_trg
BEFORE INSERT ON public.products
FOR EACH ROW EXECUTE FUNCTION public.enforce_listing_phone_verification();

-- 2) Server-side notifications ----------------------------------------------
CREATE TABLE IF NOT EXISTS public.notification_preferences (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  enabled boolean NOT NULL DEFAULT true,
  sales boolean NOT NULL DEFAULT true,
  questions boolean NOT NULL DEFAULT true,
  orders boolean NOT NULL DEFAULT true,
  notices boolean NOT NULL DEFAULT true,
  support boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  href text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  dedupe_key text,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS notifications_dedupe_key_uidx
ON public.notifications(dedupe_key)
WHERE dedupe_key IS NOT NULL;

ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Own notification preferences" ON public.notification_preferences;
CREATE POLICY "Own notification preferences"
ON public.notification_preferences
FOR ALL TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Own notifications read" ON public.notifications;
CREATE POLICY "Own notifications read"
ON public.notifications
FOR SELECT TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Own notifications update" ON public.notifications;
CREATE POLICY "Own notifications update"
ON public.notifications
FOR UPDATE TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

GRANT SELECT, UPDATE ON public.notifications TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.notification_preferences TO authenticated;
GRANT ALL ON public.notifications, public.notification_preferences TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.notification_allowed(_user_id uuid, _channel text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (
      SELECT enabled AND CASE _channel
        WHEN 'sales' THEN sales
        WHEN 'questions' THEN questions
        WHEN 'orders' THEN orders
        WHEN 'notices' THEN notices
        WHEN 'support' THEN support
        ELSE true
      END
      FROM public.notification_preferences
      WHERE user_id = _user_id
    ),
    true
  );
$$;

CREATE OR REPLACE FUNCTION public.push_notification(
  _user_id uuid,
  _type text,
  _title text,
  _body text,
  _href text,
  _channel text,
  _dedupe_key text DEFAULT NULL,
  _metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF _user_id IS NULL OR NOT public.notification_allowed(_user_id, _channel) THEN
    RETURN;
  END IF;
  INSERT INTO public.notifications(user_id,type,title,body,href,dedupe_key,metadata)
  VALUES (_user_id, left(_type,60), left(_title,120), left(coalesce(_body,''),500), left(_href,300), _dedupe_key, coalesce(_metadata,'{}'::jsonb))
  ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING;
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_purchase_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  status_changed boolean := TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM NEW.status;
BEGIN
  IF NOT status_changed THEN RETURN NEW; END IF;

  IF NEW.status = 'paid' THEN
    PERFORM public.push_notification(NEW.seller_id,'sale','Nova venda confirmada','O pedido #'||NEW.id||' foi pago.','/minhas-compras?scope=sales&order='||NEW.id,'sales','sale:'||NEW.id||':paid',jsonb_build_object('orderId',NEW.id));
    PERFORM public.push_notification(NEW.buyer_id,'order','Pagamento confirmado','O pagamento do pedido #'||NEW.id||' foi confirmado.','/minhas-compras?scope=purchases&order='||NEW.id,'orders','buyer:'||NEW.id||':paid',jsonb_build_object('orderId',NEW.id));
  ELSIF NEW.status = 'delivered_pending_confirmation' THEN
    PERFORM public.push_notification(NEW.buyer_id,'order','Pedido marcado como entregue','Confira o pedido #'||NEW.id||' e confirme o recebimento.','/minhas-compras?scope=purchases&order='||NEW.id,'orders','buyer:'||NEW.id||':delivery',jsonb_build_object('orderId',NEW.id));
  ELSIF NEW.status = 'delivered' THEN
    PERFORM public.push_notification(NEW.buyer_id,'order','Pedido concluído','O pedido #'||NEW.id||' foi concluído.','/minhas-compras?scope=purchases&order='||NEW.id,'orders','buyer:'||NEW.id||':done',jsonb_build_object('orderId',NEW.id));
    PERFORM public.push_notification(NEW.seller_id,'sale','Pedido concluído','O pedido #'||NEW.id||' foi concluído. O saldo será liberado na data informada.','/minhas-compras?scope=sales&order='||NEW.id,'sales','seller:'||NEW.id||':done',jsonb_build_object('orderId',NEW.id));
  ELSIF NEW.status = 'dispute' THEN
    PERFORM public.push_notification(NEW.seller_id,'order','Disputa aberta','Uma disputa foi aberta no pedido #'||NEW.id||'.','/minhas-compras?scope=sales&order='||NEW.id,'orders','seller:'||NEW.id||':dispute',jsonb_build_object('orderId',NEW.id));
    PERFORM public.push_notification(NEW.buyer_id,'order','Disputa aberta','A disputa do pedido #'||NEW.id||' foi registrada.','/minhas-compras?scope=purchases&order='||NEW.id,'orders','buyer:'||NEW.id||':dispute',jsonb_build_object('orderId',NEW.id));
  ELSIF NEW.status IN ('refunded','cancelled') THEN
    PERFORM public.push_notification(NEW.buyer_id,'order',CASE WHEN NEW.status='refunded' THEN 'Pedido reembolsado' ELSE 'Pedido cancelado' END,'Atualização no pedido #'||NEW.id||'.','/minhas-compras?scope=purchases&order='||NEW.id,'orders','buyer:'||NEW.id||':'||NEW.status,jsonb_build_object('orderId',NEW.id));
    PERFORM public.push_notification(NEW.seller_id,'sale',CASE WHEN NEW.status='refunded' THEN 'Reembolso concluído' ELSE 'Pedido cancelado' END,'Atualização no pedido #'||NEW.id||'.','/minhas-compras?scope=sales&order='||NEW.id,'sales','seller:'||NEW.id||':'||NEW.status,jsonb_build_object('orderId',NEW.id));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_purchase_change_trg ON public.purchases;
CREATE TRIGGER notify_purchase_change_trg
AFTER INSERT OR UPDATE OF status ON public.purchases
FOR EACH ROW EXECUTE FUNCTION public.notify_purchase_change();

CREATE OR REPLACE FUNCTION public.notify_product_question()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE seller uuid;
BEGIN
  IF TG_OP='INSERT' THEN
    SELECT seller_id INTO seller FROM public.products WHERE id=NEW.product_id;
    IF seller IS NOT NULL AND seller IS DISTINCT FROM NEW.author_id THEN
      PERFORM public.push_notification(seller,'question','Nova pergunta no anúncio',left(NEW.body,180),'/produto/'||NEW.product_id,'questions','question:'||NEW.id||':new',jsonb_build_object('productId',NEW.product_id,'questionId',NEW.id));
    END IF;
  ELSIF TG_OP='UPDATE' AND OLD.answer IS DISTINCT FROM NEW.answer AND NEW.answer IS NOT NULL THEN
    PERFORM public.push_notification(NEW.author_id,'question','O vendedor respondeu sua pergunta',left(NEW.answer,180),'/produto/'||NEW.product_id,'questions','question:'||NEW.id||':answer',jsonb_build_object('productId',NEW.product_id,'questionId',NEW.id));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_product_question_insert_trg ON public.product_questions;
CREATE TRIGGER notify_product_question_insert_trg
AFTER INSERT ON public.product_questions
FOR EACH ROW EXECUTE FUNCTION public.notify_product_question();

DROP TRIGGER IF EXISTS notify_product_question_update_trg ON public.product_questions;
CREATE TRIGGER notify_product_question_update_trg
AFTER UPDATE OF answer ON public.product_questions
FOR EACH ROW EXECUTE FUNCTION public.notify_product_question();

CREATE OR REPLACE FUNCTION public.notify_global_notice()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE p record;
BEGIN
  FOR p IN SELECT user_id FROM public.profiles LOOP
    PERFORM public.push_notification(p.user_id,'notice','Aviso da ZXMAX',left(NEW.text,300),'/configuracoes','notices','notice:'||NEW.id||':'||p.user_id,jsonb_build_object('noticeId',NEW.id));
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_global_notice_trg ON public.global_notices;
CREATE TRIGGER notify_global_notice_trg
AFTER INSERT ON public.global_notices
FOR EACH ROW EXECUTE FUNCTION public.notify_global_notice();

-- 3) Wallet ledger + delayed seller funds ------------------------------------
CREATE TABLE IF NOT EXISTS public.wallet_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric(14,2) NOT NULL CHECK (amount <> 0),
  kind text NOT NULL,
  purchase_id bigint REFERENCES public.purchases(id) ON DELETE SET NULL,
  description text NOT NULL DEFAULT '',
  dedupe_key text NOT NULL UNIQUE,
  available_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.wallet_ledger ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Own wallet ledger" ON public.wallet_ledger;
CREATE POLICY "Own wallet ledger"
ON public.wallet_ledger FOR SELECT TO authenticated
USING (user_id=auth.uid());
GRANT SELECT ON public.wallet_ledger TO authenticated;
GRANT ALL ON public.wallet_ledger TO service_role;

ALTER TABLE public.purchases
  ADD COLUMN IF NOT EXISTS funds_available_at timestamptz;

UPDATE public.app_settings
SET value = COALESCE(value,'{}'::jsonb) || jsonb_build_object(
  'min_withdraw', 20.00,
  'small_withdraw_min', 5.00,
  'small_withdraw_extra_fee', 1.00,
  'seller_release_days', 7
)
WHERE key='platform';

CREATE OR REPLACE FUNCTION public.wallet_available_balance(_user_id uuid)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  sales numeric := 0;
  ledger numeric := 0;
  reserved numeric := 0;
BEGIN
  SELECT COALESCE(SUM(COALESCE(product_amount, GREATEST(amount-COALESCE(buyer_fee,0),0))),0)
    INTO sales
  FROM public.purchases
  WHERE seller_id=_user_id
    AND seller_released=true
    AND status='delivered'
    AND (released_at IS NULL OR released_at <= now());

  SELECT COALESCE(SUM(amount),0) INTO ledger
  FROM public.wallet_ledger
  WHERE user_id=_user_id AND available_at<=now();

  SELECT COALESCE(SUM(amount),0) INTO reserved
  FROM public.withdrawals
  WHERE user_id=_user_id
    AND status IN ('pending','approved')
    AND method <> 'admin_fee';

  RETURN GREATEST(0, ROUND(sales + ledger - reserved,2));
END;
$$;

CREATE OR REPLACE FUNCTION public.withdrawable_balance(_user_id uuid, _exclude_id bigint DEFAULT NULL)
RETURNS numeric
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  balance numeric := 0;
  excluded numeric := 0;
BEGIN
  balance := public.wallet_available_balance(_user_id);
  IF _exclude_id IS NOT NULL THEN
    SELECT COALESCE(amount,0) INTO excluded
    FROM public.withdrawals
    WHERE id=_exclude_id AND user_id=_user_id AND status IN ('pending','approved');
  END IF;
  RETURN ROUND(balance + excluded,2);
END;
$$;

-- Payment application: seller funds are held for the configured period.
CREATE OR REPLACE FUNCTION public.apply_verified_payment_v2(_provider text, _event_key text, _event_type text, _purchase_id bigint, _charge_id text, _confirmed_amount numeric, _payload jsonb DEFAULT '{}'::jsonb)
RETURNS TABLE(applied boolean, resulting_status text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
declare
  purchase_row public.purchases%rowtype;
  product_row public.products%rowtype;
  delivery_text text;
  next_status text := 'paid';
  next_messages jsonb;
  qty numeric := 1;
  expected_charge text;
  settings jsonb := '{}'::jsonb;
  release_days integer := 7;
begin
  if current_user not in ('postgres', 'service_role', 'supabase_admin') then raise exception 'server_only'; end if;

  insert into public.payment_events(provider,event_key,event_type,purchase_id,charge_id,amount,payload)
  values (_provider,_event_key,_event_type,_purchase_id,_charge_id,_confirmed_amount,coalesce(_payload,'{}'::jsonb))
  on conflict (provider,event_key) do nothing;
  if not found then
    select p.status into resulting_status from public.purchases p where p.id=_purchase_id;
    applied:=false; return next; return;
  end if;

  select * into purchase_row from public.purchases where id=_purchase_id for update;
  if not found then raise exception 'purchase_not_found'; end if;
  if purchase_row.status <> 'pending' then resulting_status:=purchase_row.status; applied:=false; return next; return; end if;

  expected_charge:=coalesce(purchase_row.provider_payment_id,purchase_row.evopay_charge_id);
  if expected_charge is distinct from _charge_id then raise exception 'charge_mismatch'; end if;
  if round(purchase_row.amount*100) is distinct from round(_confirmed_amount*100) then raise exception 'amount_mismatch'; end if;

  select * into product_row from public.products where id=purchase_row.product_id for update;
  if not found then raise exception 'product_not_found'; end if;

  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  release_days:=GREATEST(5,LEAST(7,COALESCE((settings->>'seller_release_days')::integer,7)));

  next_messages:=coalesce(purchase_row.messages,'[]'::jsonb);
  qty:=coalesce(purchase_row.quantity,1);

  if product_row.delivery_type='auto' then
    select delivery_content into delivery_text from public.product_delivery where product_id=purchase_row.product_id;
    if coalesce(delivery_text,'')<>'' then
      next_status:='delivered';
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object('from','System','text','📦 ENTREGA_AUTO: '||delivery_text,'date',now()));
    end if;
  end if;

  update public.purchases
  set status=next_status,
      payment_status='paid',
      paid_at=coalesce(paid_at,now()),
      funds_available_at=coalesce(funds_available_at,now() + make_interval(days=>release_days)),
      seller_released=false,
      messages=next_messages,
      updated_at=now()
  where id=_purchase_id;

  update public.products
  set sales=coalesce(sales,0)+1,
      stock=case when stock is null then null else greatest(stock-greatest(qty,1),0) end
  where id=purchase_row.product_id;

  applied:=true; resulting_status:=next_status; return next;
end;
$$;

-- Completion and fund release are separate: delivery may finish before money is released.
CREATE OR REPLACE FUNCTION public.process_auto_release_orders()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  r record;
  processed integer := 0;
BEGIN
  -- Preserve the existing buyer-confirmation timeout, but do not release money early.
  UPDATE public.purchases
  SET status='delivered', updated_at=now(),
      messages=coalesce(messages,'[]'::jsonb)||jsonb_build_array(jsonb_build_object(
        'from','System','text','⏰ Pedido concluído automaticamente após o prazo de confirmação do comprador. O saldo continua seguindo o prazo de segurança da carteira.','date',now()
      ))
  WHERE status='delivered_pending_confirmation'
    AND delivered_pending_at IS NOT NULL
    AND delivered_pending_at <= now()-interval '3 days';

  FOR r IN
    SELECT id,seller_id FROM public.purchases
    WHERE status='delivered'
      AND seller_released=false
      AND funds_available_at IS NOT NULL
      AND funds_available_at<=now()
      AND payment_status='paid'
    FOR UPDATE
  LOOP
    UPDATE public.purchases
    SET seller_released=true,released_at=now(),updated_at=now(),
        messages=coalesce(messages,'[]'::jsonb)||jsonb_build_array(jsonb_build_object(
          'from','System','text','💰 Saldo da venda liberado na carteira após o período de segurança.','date',now()
        ))
    WHERE id=r.id;
    PERFORM public.push_notification(r.seller_id,'sale','Saldo liberado','O saldo do pedido #'||r.id||' já está disponível na carteira.','/sacar','sales','seller:'||r.id||':released',jsonb_build_object('orderId',r.id));
    processed:=processed+1;
  END LOOP;
  RETURN processed;
END;
$$;

-- Existing already-paid rows receive a deterministic 7-day hold date.
UPDATE public.purchases
SET funds_available_at = COALESCE(paid_at,created_at) + interval '7 days'
WHERE payment_status='paid' AND funds_available_at IS NULL;

-- Atomic wallet payment. Requires full document verification.
CREATE OR REPLACE FUNCTION public.pay_purchase_with_wallet(_purchase_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.purchases%rowtype;
  prod public.products%rowtype;
  prof public.profiles%rowtype;
  bal numeric;
  delivery_text text;
  next_status text := 'paid';
  next_messages jsonb;
  settings jsonb := '{}'::jsonb;
  release_days integer := 7;
  qty numeric := 1;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF;
  PERFORM pg_advisory_xact_lock(hashtext(auth.uid()::text));

  SELECT * INTO prof FROM public.profiles WHERE user_id=auth.uid();
  IF prof IS NULL OR prof.verification_status <> 'approved' THEN
    RAISE EXCEPTION 'Verifique seus documentos antes de usar o saldo da carteira.';
  END IF;

  SELECT * INTO p FROM public.purchases WHERE id=_purchase_id FOR UPDATE;
  IF p IS NULL OR p.buyer_id<>auth.uid() THEN RAISE EXCEPTION 'Pedido não encontrado'; END IF;
  IF p.status<>'pending' THEN RAISE EXCEPTION 'Este pedido não está aguardando pagamento'; END IF;
  IF p.payment_provider<>'wallet' THEN RAISE EXCEPTION 'Forma de pagamento inválida'; END IF;

  bal:=public.wallet_available_balance(auth.uid());
  IF bal < p.amount THEN RAISE EXCEPTION 'Saldo da carteira insuficiente'; END IF;

  INSERT INTO public.wallet_ledger(user_id,amount,kind,purchase_id,description,dedupe_key)
  VALUES(auth.uid(),-p.amount,'purchase',p.id,'Compra do pedido #'||p.id,'wallet:purchase:'||p.id);

  SELECT * INTO prod FROM public.products WHERE id=p.product_id FOR UPDATE;
  IF prod IS NULL THEN RAISE EXCEPTION 'Produto indisponível'; END IF;

  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  release_days:=GREATEST(5,LEAST(7,COALESCE((settings->>'seller_release_days')::integer,7)));
  qty:=coalesce(p.quantity,1);
  next_messages:=coalesce(p.messages,'[]'::jsonb);

  IF prod.delivery_type='auto' THEN
    SELECT delivery_content INTO delivery_text FROM public.product_delivery WHERE product_id=p.product_id;
    IF coalesce(delivery_text,'')<>'' THEN
      next_status:='delivered';
      next_messages:=next_messages||jsonb_build_array(jsonb_build_object('from','System','text','📦 ENTREGA_AUTO: '||delivery_text,'date',now()));
    END IF;
  END IF;

  UPDATE public.purchases
  SET status=next_status,payment_status='paid',provider_payment_id='wallet:'||id,
      paid_at=now(),funds_available_at=now()+make_interval(days=>release_days),
      seller_released=false,messages=next_messages,updated_at=now()
  WHERE id=p.id;

  UPDATE public.products
  SET sales=coalesce(sales,0)+1,
      stock=case when stock is null then null else greatest(stock-greatest(qty,1),0) end
  WHERE id=p.product_id;

  RETURN jsonb_build_object('success',true,'status',next_status,'balance',public.wallet_available_balance(auth.uid()));
END;
$$;
GRANT EXECUTE ON FUNCTION public.pay_purchase_with_wallet(bigint) TO authenticated;

-- Seller-initiated refund goes to the buyer's ZXMAX wallet while funds are held.
CREATE OR REPLACE FUNCTION public.refund_purchase_to_wallet(_purchase_id bigint, _reason text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.purchases%rowtype;
  is_admin boolean := false;
  clean_reason text := btrim(coalesce(_reason,''));
  qty numeric := 1;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF;
  SELECT * INTO p FROM public.purchases WHERE id=_purchase_id FOR UPDATE;
  IF p IS NULL THEN RAISE EXCEPTION 'Pedido não encontrado'; END IF;
  SELECT public.has_role(auth.uid(),'admin'::public.app_role) INTO is_admin;
  IF auth.uid()<>p.seller_id AND NOT is_admin THEN RAISE EXCEPTION 'Apenas o vendedor ou um administrador pode reembolsar'; END IF;
  IF p.status IN ('pending','refunded','cancelled') THEN RAISE EXCEPTION 'Este pedido não pode ser reembolsado neste estado'; END IF;
  IF char_length(clean_reason)<10 THEN RAISE EXCEPTION 'Informe um motivo com pelo menos 10 caracteres'; END IF;
  IF p.seller_released AND NOT is_admin THEN
    RAISE EXCEPTION 'O saldo desta venda já foi liberado. Abra uma disputa administrativa para concluir o reembolso.';
  END IF;

  INSERT INTO public.wallet_ledger(user_id,amount,kind,purchase_id,description,dedupe_key)
  VALUES(p.buyer_id,p.amount,'refund',p.id,'Reembolso do pedido #'||p.id,'wallet:refund:'||p.id);

  qty:=coalesce(p.quantity,1);
  UPDATE public.products
  SET stock=case when stock is null then null else stock+greatest(qty,1) end
  WHERE id=p.product_id;

  UPDATE public.purchases
  SET status='refunded',payment_status='refunded',refund_reason=clean_reason,refunded_at=now(),
      seller_released=false,released_at=null,funds_available_at=null,updated_at=now(),
      messages=coalesce(messages,'[]'::jsonb)||jsonb_build_array(jsonb_build_object(
        'from','System','text','↩️ Reembolso enviado para a carteira ZXMAX do comprador. Motivo: '||clean_reason,'date',now()
      ))
  WHERE id=p.id;

  RETURN jsonb_build_object('success',true,'status','refunded');
END;
$$;
GRANT EXECUTE ON FUNCTION public.refund_purchase_to_wallet(bigint,text) TO authenticated;

-- 4) Withdrawal rules --------------------------------------------------------
CREATE OR REPLACE FUNCTION public.request_withdrawal(_amount numeric, _method text DEFAULT 'normal', _idempotency_key text DEFAULT NULL, _retry_of bigint DEFAULT NULL, _pix_key text DEFAULT NULL)
RETURNS public.withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  w public.withdrawals;
  prof public.profiles;
  key text := COALESCE(NULLIF(TRIM(_idempotency_key), ''), gen_random_uuid()::text);
  prev public.withdrawals;
  chosen_pix text;
  req_amount numeric := ROUND(_amount, 2);
  settings jsonb := '{}'::jsonb;
  min_required numeric := 20.00;
  fixed_fee numeric := 3.50;
  small_min numeric := 5.00;
  small_extra numeric := 1.00;
  available_balance numeric := 0;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Não autenticado'; END IF;
  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  min_required:=COALESCE((settings->>'min_withdraw')::numeric,20.00);
  fixed_fee:=COALESCE((settings->>'withdraw_fee')::numeric,3.50);
  small_min:=COALESCE((settings->>'small_withdraw_min')::numeric,5.00);
  small_extra:=COALESCE((settings->>'small_withdraw_extra_fee')::numeric,1.00);

  IF _method='flex' THEN
    min_required:=small_min;
    fixed_fee:=fixed_fee+small_extra;
  ELSIF _method NOT IN ('normal','admin_fee') THEN
    RAISE EXCEPTION 'Método de saque inválido';
  END IF;

  IF req_amount IS NULL OR req_amount<min_required THEN
    RAISE EXCEPTION 'O valor mínimo de saque é R$ %',to_char(min_required,'FM999999990D00');
  END IF;
  IF fixed_fee<0 OR req_amount<=fixed_fee THEN RAISE EXCEPTION 'O valor do saque precisa ser maior que a taxa configurada'; END IF;

  PERFORM pg_advisory_xact_lock(hashtext(auth.uid()::text));
  SELECT * INTO w FROM public.withdrawals WHERE idempotency_key=key;
  IF w IS NOT NULL THEN
    IF w.user_id<>auth.uid() THEN RAISE EXCEPTION 'Chave de idempotência inválida'; END IF;
    RETURN w;
  END IF;

  SELECT * INTO prof FROM public.profiles WHERE user_id=auth.uid();
  IF prof IS NULL THEN RAISE EXCEPTION 'Perfil não encontrado'; END IF;

  IF _method='admin_fee' THEN
    IF NOT public.has_role(auth.uid(),'admin'::public.app_role) THEN RAISE EXCEPTION 'Apenas administradores podem sacar taxas da plataforma'; END IF;
  ELSE
    IF prof.verification_status<>'approved' THEN RAISE EXCEPTION 'Conclua a verificação de documentos antes de sacar'; END IF;
    available_balance:=public.wallet_available_balance(auth.uid());
    IF req_amount>available_balance THEN RAISE EXCEPTION 'Saldo disponível insuficiente para este saque'; END IF;
  END IF;

  IF _retry_of IS NOT NULL THEN
    SELECT * INTO prev FROM public.withdrawals WHERE id=_retry_of FOR UPDATE;
    IF prev IS NULL OR prev.user_id<>auth.uid() THEN RAISE EXCEPTION 'Saque original não encontrado'; END IF;
    IF prev.status<>'rejected' THEN RAISE EXCEPTION 'Só é possível reenviar um saque recusado'; END IF;
  END IF;

  chosen_pix:=COALESCE(NULLIF(TRIM(_pix_key),''),prof.pix_key,'');
  IF chosen_pix='' THEN RAISE EXCEPTION 'Cadastre uma chave Pix no perfil antes de solicitar saque'; END IF;

  INSERT INTO public.withdrawals(user_id,user_public_id,user_email,amount,fee,net_amount,method,pix_key,idempotency_key,retry_of)
  VALUES(auth.uid(),prof.public_id::text,prof.email,req_amount,ROUND(fixed_fee,2),ROUND(req_amount-fixed_fee,2),COALESCE(_method,'normal'),chosen_pix,key,_retry_of)
  RETURNING * INTO w;

  INSERT INTO public.withdrawal_events(withdrawal_id,event_type,actor_id,note)
  VALUES(w.id,CASE WHEN _retry_of IS NULL THEN 'requested' ELSE 'resubmitted' END,auth.uid(),'');
  RETURN w;
END;
$$;

-- Keep compatibility overload.
CREATE OR REPLACE FUNCTION public.request_withdrawal(_amount numeric, _method text DEFAULT 'normal', _idempotency_key text DEFAULT NULL, _retry_of bigint DEFAULT NULL)
RETURNS public.withdrawals
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  RETURN public.request_withdrawal(_amount,_method,_idempotency_key,_retry_of,NULL);
END;
$$;

-- Platform settings expose the new rules to the UI/admin.
CREATE OR REPLACE FUNCTION public.get_public_platform_fees()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE settings jsonb:='{}'::jsonb;
BEGIN
  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  RETURN jsonb_build_object(
    'buyerFee',COALESCE((settings->>'buyer_fee')::numeric,0.90),
    'minWithdraw',COALESCE((settings->>'min_withdraw')::numeric,20.00),
    'withdrawFee',COALESCE((settings->>'withdraw_fee')::numeric,3.50),
    'smallWithdrawMin',COALESCE((settings->>'small_withdraw_min')::numeric,5.00),
    'smallWithdrawExtraFee',COALESCE((settings->>'small_withdraw_extra_fee')::numeric,1.00),
    'sellerReleaseDays',COALESCE((settings->>'seller_release_days')::integer,7),
    'minProductPrice',COALESCE((settings->>'min_product_price')::numeric,2.00)
  );
END; $$;

CREATE OR REPLACE FUNCTION public.get_admin_platform_settings()
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public AS $$
DECLARE settings jsonb:='{}'::jsonb;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(),'admin'::public.app_role) THEN RAISE EXCEPTION 'Apenas administradores.' USING ERRCODE='42501'; END IF;
  SELECT value INTO settings FROM public.app_settings WHERE key='platform';
  RETURN jsonb_build_object(
    'maintenance',COALESCE((settings->>'maintenance')::boolean,false),
    'message',LEFT(COALESCE(settings->>'maintenance_message',''),300),
    'minProductPrice',COALESCE((settings->>'min_product_price')::numeric,2.00),
    'minWithdraw',COALESCE((settings->>'min_withdraw')::numeric,20.00),
    'buyerFee',COALESCE((settings->>'buyer_fee')::numeric,0.90),
    'withdrawFee',COALESCE((settings->>'withdraw_fee')::numeric,3.50),
    'smallWithdrawMin',COALESCE((settings->>'small_withdraw_min')::numeric,5.00),
    'smallWithdrawExtraFee',COALESCE((settings->>'small_withdraw_extra_fee')::numeric,1.00),
    'sellerReleaseDays',COALESCE((settings->>'seller_release_days')::integer,7)
  );
END; $$;

CREATE OR REPLACE FUNCTION public.update_platform_settings(
  _maintenance boolean,_message text,_min_product_price numeric,_min_withdraw numeric,_buyer_fee numeric,_withdraw_fee numeric,
  _small_withdraw_min numeric,_small_withdraw_extra_fee numeric,_seller_release_days integer
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE existing jsonb:='{}'::jsonb; next_settings jsonb;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(),'admin'::public.app_role) THEN RAISE EXCEPTION 'Apenas administradores.' USING ERRCODE='42501'; END IF;
  IF _message IS NULL OR char_length(btrim(_message))>300 THEN RAISE EXCEPTION 'A mensagem de manutenção deve ter até 300 caracteres.'; END IF;
  IF _min_product_price<2 OR _min_product_price>1000000 THEN RAISE EXCEPTION 'Preço mínimo inválido'; END IF;
  IF _min_withdraw<1 OR _min_withdraw>1000000 THEN RAISE EXCEPTION 'Saque mínimo inválido'; END IF;
  IF _buyer_fee<0 OR _buyer_fee>1000 THEN RAISE EXCEPTION 'Taxa do comprador inválida'; END IF;
  IF _withdraw_fee<0 OR _withdraw_fee>=_min_withdraw THEN RAISE EXCEPTION 'Taxa de saque inválida'; END IF;
  IF _small_withdraw_min<1 OR _small_withdraw_min>_min_withdraw THEN RAISE EXCEPTION 'Mínimo reduzido inválido'; END IF;
  IF _small_withdraw_extra_fee<0 OR _small_withdraw_extra_fee>=_small_withdraw_min THEN RAISE EXCEPTION 'Taxa adicional inválida'; END IF;
  IF _seller_release_days<5 OR _seller_release_days>7 THEN RAISE EXCEPTION 'Prazo de liberação deve ficar entre 5 e 7 dias'; END IF;

  SELECT value INTO existing FROM public.app_settings WHERE key='platform';
  next_settings:=COALESCE(existing,'{}'::jsonb)||jsonb_build_object(
    'maintenance',_maintenance,'maintenance_message',btrim(_message),
    'min_product_price',round(_min_product_price,2),'min_withdraw',round(_min_withdraw,2),
    'buyer_fee',round(_buyer_fee,2),'withdraw_fee',round(_withdraw_fee,2),
    'small_withdraw_min',round(_small_withdraw_min,2),'small_withdraw_extra_fee',round(_small_withdraw_extra_fee,2),
    'seller_release_days',_seller_release_days
  );
  INSERT INTO public.app_settings(key,value) VALUES('platform',next_settings)
  ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value;
  INSERT INTO public.admin_audit_log(actor_id,action,target_table,target_id,metadata)
  VALUES(auth.uid(),'platform.settings_updated','app_settings','platform',next_settings);
  RETURN public.get_admin_platform_settings();
END; $$;

-- Backwards-compatible 6-argument admin function.
CREATE OR REPLACE FUNCTION public.update_platform_settings(_maintenance boolean,_message text,_min_product_price numeric,_min_withdraw numeric,_buyer_fee numeric,_withdraw_fee numeric)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE s jsonb;
BEGIN
  SELECT value INTO s FROM public.app_settings WHERE key='platform';
  RETURN public.update_platform_settings(
    _maintenance,_message,_min_product_price,_min_withdraw,_buyer_fee,_withdraw_fee,
    COALESCE((s->>'small_withdraw_min')::numeric,5.00),
    COALESCE((s->>'small_withdraw_extra_fee')::numeric,1.00),
    COALESCE((s->>'seller_release_days')::integer,7)
  );
END; $$;

-- Tag icons (e.g. crown beside an admin/support tag).
ALTER TABLE public.user_tags ADD COLUMN IF NOT EXISTS icon_url text;


-- 5) SMS verification abuse controls ----------------------------------------
CREATE TABLE IF NOT EXISTS public.phone_verification_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  phone_hash text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('start','approved','failed')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS phone_verification_events_user_time_idx
ON public.phone_verification_events(user_id,created_at DESC);
ALTER TABLE public.phone_verification_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.phone_verification_events FROM anon, authenticated;
GRANT ALL ON public.phone_verification_events TO service_role;

-- The public view is backed by these non-contact trust columns only.
GRANT SELECT (user_id,public_id,display_name,avatar_url,is_verified_seller,created_at,phone_verified_at,verification_status)
ON public.profiles TO anon, authenticated;


-- Server wrapper used by the authenticated order-action Edge Function.
CREATE OR REPLACE FUNCTION public.refund_purchase_to_wallet_server(_purchase_id bigint, _reason text, _actor_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  p public.purchases%rowtype;
  is_admin boolean := false;
  clean_reason text := btrim(coalesce(_reason,''));
  qty numeric := 1;
BEGIN
  IF current_user NOT IN ('postgres','service_role','supabase_admin') THEN RAISE EXCEPTION 'server_only'; END IF;
  SELECT * INTO p FROM public.purchases WHERE id=_purchase_id FOR UPDATE;
  IF p IS NULL THEN RAISE EXCEPTION 'Pedido não encontrado'; END IF;
  SELECT public.has_role(_actor_id,'admin'::public.app_role) INTO is_admin;
  IF _actor_id<>p.seller_id AND NOT is_admin THEN RAISE EXCEPTION 'Apenas o vendedor ou um administrador pode reembolsar'; END IF;
  IF p.status IN ('pending','refunded','cancelled') THEN RAISE EXCEPTION 'Este pedido não pode ser reembolsado neste estado'; END IF;
  IF char_length(clean_reason)<10 THEN RAISE EXCEPTION 'Informe um motivo com pelo menos 10 caracteres'; END IF;
  IF p.seller_released AND NOT is_admin THEN RAISE EXCEPTION 'O saldo desta venda já foi liberado. Abra uma disputa administrativa.'; END IF;

  INSERT INTO public.wallet_ledger(user_id,amount,kind,purchase_id,description,dedupe_key)
  VALUES(p.buyer_id,p.amount,'refund',p.id,'Reembolso do pedido #'||p.id,'wallet:refund:'||p.id);

  qty:=coalesce(p.quantity,1);
  UPDATE public.products SET stock=case when stock is null then null else stock+greatest(qty,1) end WHERE id=p.product_id;

  UPDATE public.purchases
  SET status='refunded',payment_status='refunded',refund_reason=clean_reason,refunded_at=now(),
      seller_released=false,released_at=null,funds_available_at=null,updated_at=now(),
      messages=coalesce(messages,'[]'::jsonb)||jsonb_build_array(jsonb_build_object(
        'from','System','text','↩️ Reembolso enviado para a carteira ZXMAX do comprador. Motivo: '||clean_reason,'date',now()
      ))
  WHERE id=p.id;

  RETURN jsonb_build_object('success',true,'status','refunded');
END;
$$;
REVOKE ALL ON FUNCTION public.refund_purchase_to_wallet_server(bigint,text,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refund_purchase_to_wallet_server(bigint,text,uuid) TO service_role;


-- 6) Trusted chat roles and tag icons ----------------------------------------
ALTER TABLE public.order_messages
  ADD COLUMN IF NOT EXISTS sender_role text NOT NULL DEFAULT 'participant'
  CHECK (sender_role IN ('buyer','seller','admin','system','participant'));

CREATE OR REPLACE FUNCTION public.set_order_message_sender_role()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE p public.purchases%rowtype;
BEGIN
  SELECT * INTO p FROM public.purchases WHERE id=NEW.order_id;
  IF p IS NULL THEN RAISE EXCEPTION 'Pedido não encontrado'; END IF;
  IF auth.uid() IS NULL THEN
    NEW.sender_role := 'system';
  ELSIF public.has_role(auth.uid(),'admin'::public.app_role) THEN
    NEW.sender_role := 'admin';
  ELSIF auth.uid()=p.seller_id THEN
    NEW.sender_role := 'seller';
  ELSIF auth.uid()=p.buyer_id THEN
    NEW.sender_role := 'buyer';
  ELSE
    RAISE EXCEPTION 'Você não participa deste pedido' USING ERRCODE='42501';
  END IF;
  NEW.sender_id := COALESCE(auth.uid(),NEW.sender_id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_order_message_sender_role_trg ON public.order_messages;
CREATE TRIGGER set_order_message_sender_role_trg
BEFORE INSERT ON public.order_messages
FOR EACH ROW EXECUTE FUNCTION public.set_order_message_sender_role();

CREATE OR REPLACE FUNCTION public.create_admin_user_tag(_name text,_color text,_icon_url text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  tag_name text:=btrim(coalesce(_name,''));
  tag_color text:=lower(btrim(coalesce(_color,'')));
  clean_icon text:=btrim(coalesce(_icon_url,''));
  tag_id uuid;
BEGIN
  PERFORM public.require_admin_capability('manage_tags');
  IF char_length(tag_name)<2 OR char_length(tag_name)>32 THEN RAISE EXCEPTION 'invalid_tag_name'; END IF;
  IF tag_color !~ '^#[0-9a-f]{6}$' THEN RAISE EXCEPTION 'invalid_tag_color'; END IF;
  IF clean_icon<>'' AND clean_icon !~ '^https://[^[:space:]]+$' THEN RAISE EXCEPTION 'invalid_icon_url'; END IF;
  IF char_length(clean_icon)>800 THEN RAISE EXCEPTION 'invalid_icon_url'; END IF;
  IF EXISTS(SELECT 1 FROM public.user_tags WHERE lower(name)=lower(tag_name)) THEN RAISE EXCEPTION 'tag_already_exists'; END IF;
  INSERT INTO public.user_tags(name,color,icon_url) VALUES(tag_name,tag_color,NULLIF(clean_icon,'')) RETURNING id INTO tag_id;
  INSERT INTO public.admin_audit_log(actor_id,action,target_table,target_id,metadata)
  VALUES(auth.uid(),'tag.created','user_tags',tag_id::text,jsonb_build_object('name',tag_name,'color',tag_color,'icon',NULLIF(clean_icon,'')));
  RETURN tag_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.create_admin_user_tag(text,text,text) TO authenticated;

CREATE OR REPLACE FUNCTION public.get_admin_user_tags()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE result jsonb;
BEGIN
  PERFORM public.require_admin_capability('manage_tags');
  SELECT jsonb_build_object(
    'tags',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',t.id,'name',t.name,'color',t.color,'iconUrl',t.icon_url) ORDER BY lower(t.name)) FROM public.user_tags t),'[]'::jsonb),
    'assignments',COALESCE((
      SELECT jsonb_object_agg(tagged.public_id::text,tagged.tag_ids)
      FROM (
        SELECT p.public_id,jsonb_agg(a.tag_id::text ORDER BY a.tag_id::text) tag_ids
        FROM public.user_tag_assignments a JOIN public.profiles p ON p.user_id=a.user_id
        GROUP BY p.public_id
      ) tagged
    ),'{}'::jsonb)
  ) INTO result;
  RETURN result;
END;
$$;
