-- ZXMAX · Segurança de gateways, moderação auditável e proveniência de pagamentos.
-- Migração aditiva e idempotente: não apaga pedidos, produtos ou perfis existentes.

ALTER TABLE public.purchases
  ADD COLUMN IF NOT EXISTS payment_provider text;

ALTER TABLE public.purchases
  DROP CONSTRAINT IF EXISTS purchases_payment_provider_valid;

ALTER TABLE public.purchases
  ADD CONSTRAINT purchases_payment_provider_valid
  CHECK (payment_provider IS NULL OR payment_provider IN ('zennith_pix', 'vexopay_pix', 'crypto', 'card', 'boleto')) NOT VALID;

GRANT SELECT (payment_provider) ON public.purchases TO authenticated;

-- Não há mais aprovação pelo navegador. Toda decisão de moderação é executada
-- no banco, valida o papel do usuário e grava a trilha antes de devolver a linha.
CREATE OR REPLACE FUNCTION public.moderate_product(
  _product_id bigint,
  _approved boolean,
  _reason text DEFAULT NULL
)
RETURNS public.products
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  changed public.products;
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_role(auth.uid(), 'admin'::public.app_role) THEN
    RAISE EXCEPTION 'Apenas administradores podem moderar anúncios' USING ERRCODE = '42501';
  END IF;

  UPDATE public.products
  SET approved = _approved,
      updated_at = now()
  WHERE id = _product_id
  RETURNING * INTO changed;

  IF changed IS NULL THEN
    RAISE EXCEPTION 'Anúncio não encontrado' USING ERRCODE = 'P0002';
  END IF;

  INSERT INTO public.admin_audit_log (actor_id, action, target_table, target_id, reason, metadata)
  VALUES (
    auth.uid(),
    CASE WHEN _approved THEN 'product.approved' ELSE 'product.unapproved' END,
    'products',
    _product_id::text,
    NULLIF(btrim(_reason), ''),
    jsonb_build_object('seller_id', changed.seller_id, 'name', changed.name)
  );

  RETURN changed;
END;
$$;

REVOKE ALL ON FUNCTION public.moderate_product(bigint, boolean, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.moderate_product(bigint, boolean, text) TO authenticated, service_role;

-- A trigger de aprovação existente continua impedindo autoaprovação por
-- vendedores. A UI administrativa usa o RPC acima para obter uma trilha
-- explícita, enquanto vendedores ainda podem pausar o próprio anúncio.

-- Registro mínimo de segurança para tentativas de autenticação e ações críticas.
CREATE TABLE IF NOT EXISTS public.security_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid NULL,
  event_type text NOT NULL,
  outcome text NOT NULL CHECK (outcome IN ('success', 'failure', 'blocked')),
  context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_security_events_created_at ON public.security_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_actor_created ON public.security_events(actor_id, created_at DESC);

ALTER TABLE public.security_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.security_events FROM anon, authenticated;
GRANT ALL ON public.security_events TO service_role;

CREATE POLICY "Admins read security events"
ON public.security_events FOR SELECT TO authenticated
USING (public.has_role(auth.uid(), 'admin'::public.app_role));

-- A configuração armazenada no banco contém somente disponibilidade, URL e taxas.
-- Segredos devem ser definidos como secrets de Edge Functions, nunca no JSON.
COMMENT ON TABLE public.app_settings IS 'Configuração não sensível do ZXMAX. Credenciais de OAuth e gateways vivem exclusivamente nos secrets das Edge Functions.';
